import { createHash } from "node:crypto";

const statuses = new Set(["pending", "accepted", "rejected", "resolved", "superseded"]);
export const findingTypes = new Set(["create_issue", "add_comment", "update_issue", "close_issue"]);
const hash = (value) => createHash("sha256").update(value).digest("hex");
const slug = /^[a-z0-9][a-z0-9-]*$/;
const repository = /^[A-Za-z0-9][A-Za-z0-9-]*\/[A-Za-z0-9._-]+$/;
const assert = (condition, message) => { if (!condition) throw new Error(`Review inbox: ${message}`); };
const bot = (item) => item.user?.type === "Bot";

// Render every untrusted character as an HTML entity. In particular, Markdown
// links, mentions, bare URLs, HTML and issue references cannot create side effects.
export function inert(value) {
  return Array.from(String(value), (character) => `&#${character.codePointAt(0)};`).join("");
}

export function validateHandoff(handoff, expected) {
  assert(handoff?.authorized === true && handoff.control_role === "worker", "unauthorized worker handoff");
  for (const [field, value] of Object.entries({
    campaign: expected.campaign, worker: expected.worker, target_repo: expected.target,
    safe_output_repo: expected.destination, safe_output_mode: "review",
  })) assert(handoff[field] === value, `handoff ${field} mismatch`);
  assert(repository.test(expected.target) && repository.test(expected.destination), "invalid repository");
  assert(slug.test(expected.campaign) && slug.test(expected.worker), "invalid campaign or worker");
  assert(handoff.policy_source?.repository === expected.control
    && handoff.policy_source?.sha === expected.sha && /^[a-f0-9]{40}$/i.test(expected.sha),
  "handoff is not from the exact control workflow SHA");
  assert(expected.destination.toLowerCase() !== expected.target.toLowerCase()
    || expected.destination.toLowerCase() === expected.control.toLowerCase(), "review destination is the target");
}

export function normalizeFinding(item, scope, priorIdentity) {
  assert(item && findingTypes.has(item.type), "unsupported finding");
  assert(typeof (item.body ?? "") === "string" && typeof (item.title ?? "") === "string", "invalid finding text");
  const marker = (item.body ?? "").match(/<!-- cao-finding-key: ([A-Za-z0-9._:/-]{1,160}) -->/);
  // Existing safe-output schemas do not accept arbitrary new fields. A structured
  // key in the body works with every existing issue/comment primitive.
  const explicit = marker?.[1];
  const targetItem = item.issue_number ?? item.item_number;
  if (targetItem !== undefined) assert(Number.isSafeInteger(targetItem) && targetItem > 0, "invalid target item");
  const title = (item.title ?? "").replace(/^\[[^\]]+\]\s*/, "").normalize("NFKC")
    .toLowerCase().replace(/\s+/g, " ").trim();
  const key = explicit ?? priorIdentity?.key ?? (targetItem ? `item:${targetItem}` : `title:${title}`);
  assert(explicit || targetItem || title, "finding needs a stable title, item identifier or explicit key");
  const identity = { target: scope.target.toLowerCase(), worker: scope.worker, key };
  const id = hash(JSON.stringify(identity)).slice(0, 24);
  const proposal = {
    identity, id, title: item.title || `Target item ${targetItem ?? explicit}`,
    body: (item.body ?? "").replace(/<!-- cao-finding-key: [A-Za-z0-9._:/-]{1,160} -->/g, ""),
    status: item.type === "close_issue" ? "resolved" : "pending",
  };
  const serialized = JSON.stringify(proposal);
  assert(Buffer.byteLength(serialized) <= 12000
    && inert(proposal.title + proposal.body).length + Buffer.byteLength(serialized) * 2 <= 50000,
  "finding too large; retain detail in a review bundle");
  return { ...proposal, revision: hash(JSON.stringify(proposal)) };
}

function provenance(scope) {
  return `<!-- gh-aw-workflow-id: ${scope.workflow} -->\n`
    + `<!-- gh-aw-agentic-workflow: ${scope.workflow}, workflow_id: ${scope.workflow}, run: ${scope.runUrl} -->\n`
    + `\n*Generated by ${scope.workflow} ([workflow run](${scope.runUrl})).*`;
}

function pack(kind, data, text, scope) {
  const encoded = Buffer.from(JSON.stringify(data)).toString("base64");
  const content = `<!-- cao-review-${kind}: ${encoded} -->\n${text}\n\n${provenance(scope)}`;
  const body = `${content}\n<!-- cao-review-seal: ${hash(content)} -->`;
  assert(body.length <= 60000, "generated surface exceeds GitHub body limit");
  return body;
}

function unpack(kind, body) {
  const match = body?.match(new RegExp(`^<!-- cao-review-${kind}: ([A-Za-z0-9+/=]+) -->\\n`));
  assert(match, `missing ${kind} state`);
  const seal = body.match(/\n<!-- cao-review-seal: ([a-f0-9]{64}) -->$/);
  assert(seal && hash(body.slice(0, seal.index)) === seal[1], `corrupt or human-edited ${kind} surface`);
  const data = JSON.parse(Buffer.from(match[1], "base64").toString("utf8"));
  assert(data?.version === 1, `unsupported ${kind} state`);
  return data;
}

const scopeKey = (scope) => `${scope.control.toLowerCase()}:${scope.campaign}`;
const ledgerDigest = (records) => hash(JSON.stringify(records.map(({ comment, data }) => [comment.id, data.event])));

function readRecords(comments, scope, author) {
  const records = [];
  for (const comment of comments) {
    if (!comment.body?.startsWith("<!-- cao-review-record:")) continue;
    assert(bot(comment) && comment.user.login === author, "record is not bot-owned");
    const data = unpack("record", comment.body);
    assert(data.scope === scopeKey(scope), "record scope mismatch");
    assert(/^[a-f0-9]{64}$/.test(data.event) && /^[a-f0-9]{24}$/.test(data.finding?.id)
      && statuses.has(data.finding.status) && /^[a-f0-9]{64}$/.test(data.finding.revision ?? "")
      && repository.test(data.finding.identity?.target ?? "") && slug.test(data.finding.identity?.worker ?? "")
      && typeof data.finding.identity?.key === "string" && data.finding.identity.key.length > 0
      && typeof data.finding.body === "string" && typeof data.finding.title === "string"
      && Number.isSafeInteger(data.finding.decision) && data.finding.decision >= 0,
    "invalid finding state");
    assert(hash(JSON.stringify(data.finding.identity)).slice(0, 24) === data.finding.id, "finding identity mismatch");
    assert(data.event === hash(JSON.stringify(data.finding)), "record event mismatch");
    records.push({ comment, data });
  }
  return records.sort((left, right) => left.comment.id - right.comment.id);
}

function summary(scope, records, entries) {
  const counts = [...statuses].map((status) => `${status}: ${[...entries.values()].filter((entry) => entry.finding.status === status).length}`);
  const actionable = [...entries.values()].filter(({ finding }) => ["pending", "accepted"].includes(finding.status))
    .sort((a, b) => Number(a.finding.status === "accepted") - Number(b.finding.status === "accepted")
      || a.finding.id.localeCompare(b.finding.id));
  const rows = actionable.slice(0, 40).map(({ finding, comment }) => {
    const title = Array.from(finding.title.replace(/^\[[^\]]+\]\s*/, "").replace(/\s+/g, " ").trim());
    const shortTitle = title.slice(0, 80).join("") + (title.length > 80 ? "…" : "");
    return `| \`${finding.id}\` | ${inert(shortTitle)} | ${finding.status} | ${inert(finding.identity.target)} | ${inert(finding.identity.worker)} | [detail](#issuecomment-${comment.id}) |`;
  });
  return pack("inbox", {
    version: 1, scope: scopeKey(scope),
    checkpoint: { through: records.at(-1)?.comment.id ?? 0, count: records.length, digest: ledgerDigest(records) },
  }, `# ${scope.campaign} review inbox\n\n${counts.join(" · ")}\n\n`
    + "| Finding | Title | Status | Target | Worker | Evidence |\n|---|---|---|---|---|---|\n" + rows.join("\n")
    + (actionable.length ? "" : "\nNo actionable findings.")
    + `\n\nShowing at most 40 of ${actionable.length} actionable findings (${entries.size} total). All detail and state remain in bot-owned comments.`
    + "\n\nOn a separate human comment, use `/cao-review FINDING_ID STATUS` with "
    + "`pending`, `accepted`, `rejected`, `resolved` or `superseded`. Only repository writers may decide."
    + "\nAcceptance records a review decision only; it never enables live execution.", scope);
}

async function authorized(api, scope, login) {
  const response = await api.rest.repos.getCollaboratorPermissionLevel({
    ...scope.repo, username: login,
  });
  return ["admin", "maintain", "write"].includes(response.data.permission)
    || response.data.user?.permissions?.push === true;
}

function validateScope(scope) {
  assert(slug.test(scope.campaign) && slug.test(scope.worker) && repository.test(scope.control)
    && repository.test(scope.destination) && repository.test(scope.target), "invalid publishing scope");
  assert(/^[a-zA-Z0-9_-]+$/.test(scope.workflow), "invalid workflow provenance");
  const run = new URL(scope.runUrl);
  assert(run.protocol === "https:" && !run.username && !run.password
    && run.pathname === `/${scope.control}/actions/runs/${scope.runId}`
    && /^\d+$/.test(String(scope.runId)), "invalid workflow run provenance");
}

// API errors are intentionally propagated. Never use search (its cap can hide
// an existing inbox) or reinterpret a failed page as an empty repository.
export async function publishInbox(api, inputScope, items, { staged = false, now = () => new Date().toISOString() } = {}) {
  validateScope(inputScope);
  const scope = { ...inputScope, repo: Object.fromEntries(["owner", "repo"].map((key, index) => [key, inputScope.destination.split("/")[index]])) };
  assert(Array.isArray(items), "invalid output items");
  const findingItems = items.filter((item) => findingTypes.has(item.type));
  // Validate before any API mutation, even when a legacy identifier later
  // supplies the stable identity for an update.
  findingItems.forEach((item) => normalizeFinding(item, scope));
  const proposals = [];
  const issues = await api.paginate(api.rest.issues.listForRepo, { ...scope.repo, state: "all", per_page: 100 });
  const candidates = issues.filter((issue) => !issue.pull_request
    && issue.title === `[CAO review] ${scope.campaign}`);
  const matching = [];
  for (const issue of candidates) {
    const data = unpack("inbox", issue.body);
    if (data.scope === scopeKey(scope)) {
      assert(bot(issue), "inbox is not bot-owned");
      matching.push(issue);
    }
  }
  assert(matching.length <= 1, "multiple campaign inboxes");
  let inbox = matching[0];
  let records = [];
  let comments = [];
  if (inbox) {
    comments = await api.paginate(api.rest.issues.listComments, { ...scope.repo, issue_number: inbox.number, per_page: 100 });
    records = readRecords(comments, scope, inbox.user.login);
    const checkpoint = unpack("inbox", inbox.body).checkpoint;
    assert(checkpoint && Number.isSafeInteger(checkpoint.through) && Number.isSafeInteger(checkpoint.count), "invalid checkpoint");
    const committed = records.filter(({ comment }) => comment.id <= checkpoint.through);
    assert(committed.length === checkpoint.count && ledgerDigest(committed) === checkpoint.digest, "missing or corrupt durable records");
  }
  const entries = new Map(records.map((record) => [record.data.finding.id, { finding: record.data.finding, comment: record.comment }]));
  // Legacy findings require BOTH explicit campaign/worker labels AND gh-aw
  // provenance. Their full bodies/comments stay untouched; links preserve
  // all prior human discussion, including decisions we cannot safely parse.
  const legacy = issues.filter((issue) => !issue.pull_request && issue.number !== inbox?.number
    && issue.labels?.some((label) => (label.name ?? label) === scope.campaign)
    && issue.labels?.some((label) => (label.name ?? label) === `${scope.campaign}:${scope.worker}`)
    && bot(issue) && issue.body?.includes(`<!-- gh-aw-workflow-id: ${scope.workflow} -->`));
  const legacyIdentity = new Map();
  for (const issue of legacy) {
    const target = issue.body.match(/(?:Target repository|target_repo):\s*`?([A-Za-z0-9-]+\/[A-Za-z0-9._-]+)/i)?.[1];
    if (target?.toLowerCase() !== scope.target.toLowerCase()) continue;
    const finding = normalizeFinding({ type: "create_issue", title: issue.title, body: issue.body }, scope);
    legacyIdentity.set(issue.number, finding);
    // Fetch all comments even though we leave their text in place. A partial
    // migration must not imply that human decisions have been fully inspected.
    const discussion = await api.paginate(api.rest.issues.listComments, { ...scope.repo, issue_number: issue.number, per_page: 100 });
    const existing = entries.get(finding.id);
    if (!existing) proposals.push({ ...finding, legacy: issue.number });
    for (const comment of discussion) {
      if (comment.user?.type !== "Bot") {
        comments.push({ ...comment, body: comment.body?.replace(/^\/cao-review (pending|accepted|rejected|resolved|superseded)\s*$/, `/cao-review ${finding.id} $1`) });
      }
    }
  }
  for (const item of findingItems) {
    const old = legacyIdentity.get(item.issue_number ?? item.item_number);
    const isReviewItem = item.repo?.toLowerCase() === scope.destination.toLowerCase()
      || (!item.repo && ["update_issue", "close_issue"].includes(item.type));
    const mapped = old && isReviewItem && item.type !== "create_issue";
    proposals.push(normalizeFinding(mapped ? { ...item, title: item.title || old.title } : item,
      scope, mapped ? old.identity : undefined));
  }
  if (staged) return { staged: true, findings: proposals.length, inbox: inbox?.number,
    preview: proposals.slice(0, 40).map((finding) => ({
      id: finding.id, title: inert(finding.title), target: inert(finding.identity.target),
      worker: finding.identity.worker, status: entries.get(finding.id)?.finding.status ?? finding.status,
    })) };
  if (!inbox && !proposals.length) return { findings: 0 };
  if (!inbox) {
    inbox = (await api.rest.issues.create({ ...scope.repo, title: `[CAO review] ${scope.campaign}`,
      body: summary(scope, [], new Map()) })).data;
    assert(bot(inbox), "created inbox is not bot-owned");
  }
  const add = async (finding) => {
    const event = hash(JSON.stringify(finding));
    if (records.at(-1)?.data.event === event) return;
    const detail = `## ${inert(finding.title)}\n\nFinding: \`${finding.id}\` · ${finding.status}\n\n`
      + `First seen: ${inert(finding.firstSeen)} · Updated: ${inert(finding.updatedAt)}\n\n`
      + (finding.decisionAt ? `Human decision: ${inert(finding.decisionAt)}\n\n` : "")
      + `${inert(finding.body)}\n\n`
      + (finding.legacy ? `[Original review issue and human discussion](${new URL(scope.runUrl).origin}/${scope.destination}/issues/${finding.legacy})\n\n` : "")
      + `Evidence: [original agent output and review bundles](${scope.runUrl}#artifacts).`;
    const data = { version: 1, scope: scopeKey(scope), event, finding };
    const comment = (await api.rest.issues.createComment({ ...scope.repo, issue_number: inbox.number,
      body: pack("record", data, detail, scope) })).data;
    assert(bot(comment) && comment.user.login === inbox.user.login, "publisher bot identity changed");
    const record = { comment, data };
    records.push(record);
    entries.set(finding.id, { finding, comment });
  };
  for (const proposal of proposals) {
    const previous = entries.get(proposal.id)?.finding;
    if (previous?.revision === proposal.revision) continue;
    const updatedAt = now();
    const firstSeen = previous?.firstSeen
      ?? records.find(({ data }) => data.finding.id === proposal.id)?.comment.created_at ?? updatedAt;
    await add({ ...proposal, legacy: proposal.legacy ?? previous?.legacy,
      status: previous?.decision > 0 ? previous.status
        : proposal.status === "resolved" ? "resolved" : previous?.status ?? proposal.status,
      decision: previous?.decision ?? 0, decisionAt: previous?.decisionAt,
      firstSeen, updatedAt });
  }
  for (const comment of comments.sort((left, right) => left.id - right.id)) {
    if (comment.user?.type === "Bot") continue;
    const command = comment.body?.trim().match(/^\/cao-review ([a-f0-9]{24}) (pending|accepted|rejected|resolved|superseded)$/);
    if (!command) continue;
    const previous = entries.get(command[1])?.finding;
    if (!previous || comment.id <= previous.decision) continue;
    if (!await authorized(api, scope, comment.user.login)) continue;
    const decisionAt = comment.updated_at ?? comment.created_at;
    await add({ ...previous, status: command[2], decision: comment.id, decisionAt,
      firstSeen: previous.firstSeen
        ?? records.find(({ data }) => data.finding.id === previous.id)?.comment.created_at ?? now(),
      updatedAt: now() });
  }
  // Footer provenance stays unchanged on no-op reruns as well.
  const next = summary(scope, records, entries);
  const previousSummary = unpack("inbox", inbox.body);
  const nextSummary = unpack("inbox", next);
  if (JSON.stringify(previousSummary) !== JSON.stringify(nextSummary)) {
    await api.rest.issues.update({ ...scope.repo, issue_number: inbox.number, body: next });
  }
  return { inbox: inbox.number, findings: entries.size };
}
