-- Generated from server/spec/storage.tsp. Do not edit.

-- Fresh database only. Opaque artifacts remain external.

-- Inventory normalization contract: 4bac781c5f40c973c3765bdc44498a95647e58a7b83dd597b7c7db8b5263daa7

CREATE TABLE IF NOT EXISTS cao_contract (
  digest TEXT NOT NULL,
  PRIMARY KEY (digest)
);

CREATE TABLE IF NOT EXISTS cao_state (
  namespace TEXT NOT NULL,
  revision BIGINT NOT NULL,
  data_revision TEXT NOT NULL,
  evaluated_at TIMESTAMPTZ NOT NULL,
  schema_version BIGINT NOT NULL,
  PRIMARY KEY (namespace)
);

CREATE TABLE IF NOT EXISTS cao_quality (
  namespace TEXT NOT NULL,
  collection TEXT NOT NULL,
  availability TEXT NOT NULL,
  completeness TEXT NOT NULL,
  freshness TEXT NOT NULL,
  as_of TIMESTAMPTZ,
  retrieved_at TIMESTAMPTZ,
  PRIMARY KEY (namespace, collection),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (collection IN ('$repositories','$campaigns','$workflows','$runs','$audits','$domains','$evals','$experiments','$evalObservations','$experimentAssignments','$friction','$graders','$graderObservations','$issues','$operationalValues','$outcomes','$security-findings','$skills','$tools','$transactions','work-items')),
  CHECK (availability IN ('available','empty','unavailable')),
  CHECK (completeness IN ('complete','partial','unknown')),
  CHECK (freshness IN ('current','stale','unknown'))
);

CREATE TABLE IF NOT EXISTS cao_repository_lifecycle (
  namespace TEXT NOT NULL,
  id TEXT NOT NULL,
  owner TEXT NOT NULL,
  name TEXT NOT NULL,
  lifecycle TEXT NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (namespace, id),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (lifecycle IN ('active','archived','deleted'))
);

CREATE INDEX IF NOT EXISTS cao_repository_lifecycle_coordinate ON cao_repository_lifecycle (namespace, owner, name);

CREATE TABLE IF NOT EXISTS repositories (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  name TEXT,
  observed_at TIMESTAMPTZ,
  organization_link_object BOOLEAN,
  organization_link_relation TEXT,
  organization_link_href TEXT,
  organization_link_label TEXT,
  owner TEXT,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  rollout_mode TEXT,
  lifecycle TEXT,
  visibility TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 15),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS campaigns (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  ai_credit_allowance NUMERIC,
  campaign_link_object BOOLEAN,
  campaign_link_relation TEXT,
  campaign_link_href TEXT,
  campaign_link_label TEXT,
  current_version TEXT,
  description TEXT,
  enabled BOOLEAN,
  experimental BOOLEAN,
  icon TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  inventory_warnings BIGINT,
  max_repositories BIGINT,
  min_version TEXT,
  mode TEXT,
  monthly_ai_credit_budget NUMERIC,
  name TEXT,
  observed_at TIMESTAMPTZ,
  readme TEXT,
  readme_path TEXT,
  rollout_percent NUMERIC,
  slug TEXT,
  update_state TEXT,
  version TEXT,
  worker_count BIGINT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 25),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS workflows (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  admission_reason TEXT,
  admission_status TEXT,
  campaign_id TEXT,
  created_at TIMESTAMPTZ,
  external_link_object BOOLEAN,
  external_link_relation TEXT,
  external_link_href TEXT,
  external_link_label TEXT,
  gh_aw_current_version TEXT,
  gh_aw_update_state TEXT,
  gh_aw_version TEXT,
  github_id TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  inventory_ready BOOLEAN,
  max_ai_credits NUMERIC,
  name TEXT,
  observed_at TIMESTAMPTZ,
  organization_link_object BOOLEAN,
  organization_link_relation TEXT,
  organization_link_href TEXT,
  organization_link_label TEXT,
  path TEXT,
  registry_state TEXT,
  repository_id TEXT,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  role TEXT,
  rollout_mode TEXT,
  state TEXT,
  updated_at TIMESTAMPTZ,
  workflow_link_object BOOLEAN,
  workflow_link_relation TEXT,
  workflow_link_href TEXT,
  workflow_link_label TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 36),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  FOREIGN KEY (namespace, campaign_id) REFERENCES campaigns(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (repository_id IS NOT NULL AND repository_id <> ''),
  FOREIGN KEY (namespace, repository_id) REFERENCES repositories(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS workflows_campaign_id ON workflows (namespace, campaign_id, ordinal);

CREATE INDEX IF NOT EXISTS workflows_repository_id ON workflows (namespace, repository_id, ordinal);

CREATE TABLE IF NOT EXISTS runs (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  task_domain_label TEXT,
  session_label TEXT,
  behavior_evidence_object BOOLEAN,
  behavior_evidence_origin_id TEXT,
  behavior_evidence_source TEXT,
  behavior_evidence_status TEXT,
  behavior_evidence_timestamp TIMESTAMPTZ,
  behavior_evidence_observed_at TIMESTAMPTZ,
  behavior_evidence_sequence BIGINT,
  behavior_evidence_source_sequence BIGINT,
  behavior_evidence_payload_ref TEXT,
  behavior_evidence_attempt BIGINT,
  behavior_evidence_provenance_source TEXT,
  behavior_evidence_provenance_source_id TEXT,
  behavior_evidence_provenance_observed_at TIMESTAMPTZ,
  behavior_evidence_template_version BIGINT,
  session_evidence_object BOOLEAN,
  session_evidence_origin_id TEXT,
  session_evidence_source TEXT,
  session_evidence_status TEXT,
  session_evidence_timestamp TIMESTAMPTZ,
  session_evidence_observed_at TIMESTAMPTZ,
  session_evidence_sequence BIGINT,
  session_evidence_source_sequence BIGINT,
  session_evidence_payload_ref TEXT,
  session_evidence_attempt BIGINT,
  session_evidence_provenance_source TEXT,
  session_evidence_provenance_source_id TEXT,
  session_evidence_provenance_observed_at TIMESTAMPTZ,
  session_evidence_template_version BIGINT,
  started_evidence_object BOOLEAN,
  started_evidence_origin_id TEXT,
  started_evidence_source TEXT,
  started_evidence_status TEXT,
  started_evidence_timestamp TIMESTAMPTZ,
  started_evidence_observed_at TIMESTAMPTZ,
  started_evidence_sequence BIGINT,
  started_evidence_source_sequence BIGINT,
  started_evidence_payload_ref TEXT,
  started_evidence_attempt BIGINT,
  started_evidence_provenance_source TEXT,
  started_evidence_provenance_source_id TEXT,
  started_evidence_provenance_observed_at TIMESTAMPTZ,
  started_evidence_template_version BIGINT,
  completed_evidence_object BOOLEAN,
  completed_evidence_origin_id TEXT,
  completed_evidence_source TEXT,
  completed_evidence_status TEXT,
  completed_evidence_timestamp TIMESTAMPTZ,
  completed_evidence_observed_at TIMESTAMPTZ,
  completed_evidence_sequence BIGINT,
  completed_evidence_source_sequence BIGINT,
  completed_evidence_payload_ref TEXT,
  completed_evidence_attempt BIGINT,
  completed_evidence_provenance_source TEXT,
  completed_evidence_provenance_source_id TEXT,
  completed_evidence_provenance_observed_at TIMESTAMPTZ,
  completed_evidence_template_version BIGINT,
  failure_evidence_object BOOLEAN,
  failure_evidence_origin_id TEXT,
  failure_evidence_source TEXT,
  failure_evidence_status TEXT,
  failure_evidence_timestamp TIMESTAMPTZ,
  failure_evidence_observed_at TIMESTAMPTZ,
  failure_evidence_sequence BIGINT,
  failure_evidence_source_sequence BIGINT,
  failure_evidence_payload_ref TEXT,
  failure_evidence_attempt BIGINT,
  failure_evidence_provenance_source TEXT,
  failure_evidence_provenance_source_id TEXT,
  failure_evidence_provenance_observed_at TIMESTAMPTZ,
  failure_evidence_template_version BIGINT,
  usage_evidence_object BOOLEAN,
  usage_evidence_origin_id TEXT,
  usage_evidence_source TEXT,
  usage_evidence_status TEXT,
  usage_evidence_timestamp TIMESTAMPTZ,
  usage_evidence_observed_at TIMESTAMPTZ,
  usage_evidence_sequence BIGINT,
  usage_evidence_source_sequence BIGINT,
  usage_evidence_payload_ref TEXT,
  usage_evidence_attempt BIGINT,
  usage_evidence_provenance_source TEXT,
  usage_evidence_provenance_source_id TEXT,
  usage_evidence_provenance_observed_at TIMESTAMPTZ,
  usage_evidence_template_version BIGINT,
  safe_output_count_evidence_object BOOLEAN,
  safe_output_count_evidence_origin_id TEXT,
  safe_output_count_evidence_source TEXT,
  safe_output_count_evidence_status TEXT,
  safe_output_count_evidence_timestamp TIMESTAMPTZ,
  safe_output_count_evidence_observed_at TIMESTAMPTZ,
  safe_output_count_evidence_sequence BIGINT,
  safe_output_count_evidence_source_sequence BIGINT,
  safe_output_count_evidence_payload_ref TEXT,
  safe_output_count_evidence_attempt BIGINT,
  safe_output_count_evidence_provenance_source TEXT,
  safe_output_count_evidence_provenance_source_id TEXT,
  safe_output_count_evidence_provenance_observed_at TIMESTAMPTZ,
  safe_output_count_evidence_template_version BIGINT,
  assessment_heavy_execution_object BOOLEAN,
  assessment_heavy_execution_origin_id TEXT,
  assessment_heavy_execution_source TEXT,
  assessment_heavy_execution_status TEXT,
  assessment_heavy_execution_timestamp TIMESTAMPTZ,
  assessment_heavy_execution_observed_at TIMESTAMPTZ,
  assessment_heavy_execution_sequence BIGINT,
  assessment_heavy_execution_source_sequence BIGINT,
  assessment_heavy_execution_payload_ref TEXT,
  assessment_heavy_execution_attempt BIGINT,
  assessment_heavy_execution_provenance_source TEXT,
  assessment_heavy_execution_provenance_source_id TEXT,
  assessment_heavy_execution_provenance_observed_at TIMESTAMPTZ,
  assessment_heavy_execution_template_version BIGINT,
  assessment_smaller_model_object BOOLEAN,
  assessment_smaller_model_origin_id TEXT,
  assessment_smaller_model_source TEXT,
  assessment_smaller_model_status TEXT,
  assessment_smaller_model_timestamp TIMESTAMPTZ,
  assessment_smaller_model_observed_at TIMESTAMPTZ,
  assessment_smaller_model_sequence BIGINT,
  assessment_smaller_model_source_sequence BIGINT,
  assessment_smaller_model_payload_ref TEXT,
  assessment_smaller_model_attempt BIGINT,
  assessment_smaller_model_provenance_source TEXT,
  assessment_smaller_model_provenance_source_id TEXT,
  assessment_smaller_model_provenance_observed_at TIMESTAMPTZ,
  assessment_smaller_model_template_version BIGINT,
  assessment_deterministic_object BOOLEAN,
  assessment_deterministic_origin_id TEXT,
  assessment_deterministic_source TEXT,
  assessment_deterministic_status TEXT,
  assessment_deterministic_timestamp TIMESTAMPTZ,
  assessment_deterministic_observed_at TIMESTAMPTZ,
  assessment_deterministic_sequence BIGINT,
  assessment_deterministic_source_sequence BIGINT,
  assessment_deterministic_payload_ref TEXT,
  assessment_deterministic_attempt BIGINT,
  assessment_deterministic_provenance_source TEXT,
  assessment_deterministic_provenance_source_id TEXT,
  assessment_deterministic_provenance_observed_at TIMESTAMPTZ,
  assessment_deterministic_template_version BIGINT,
  recommendation_review_errors_object BOOLEAN,
  recommendation_review_errors_origin_id TEXT,
  recommendation_review_errors_source TEXT,
  recommendation_review_errors_status TEXT,
  recommendation_review_errors_timestamp TIMESTAMPTZ,
  recommendation_review_errors_observed_at TIMESTAMPTZ,
  recommendation_review_errors_sequence BIGINT,
  recommendation_review_errors_source_sequence BIGINT,
  recommendation_review_errors_payload_ref TEXT,
  recommendation_review_errors_attempt BIGINT,
  recommendation_review_errors_provenance_source TEXT,
  recommendation_review_errors_provenance_source_id TEXT,
  recommendation_review_errors_provenance_observed_at TIMESTAMPTZ,
  recommendation_review_errors_template_version BIGINT,
  recommendation_trim_execution_object BOOLEAN,
  recommendation_trim_execution_origin_id TEXT,
  recommendation_trim_execution_source TEXT,
  recommendation_trim_execution_status TEXT,
  recommendation_trim_execution_timestamp TIMESTAMPTZ,
  recommendation_trim_execution_observed_at TIMESTAMPTZ,
  recommendation_trim_execution_sequence BIGINT,
  recommendation_trim_execution_source_sequence BIGINT,
  recommendation_trim_execution_payload_ref TEXT,
  recommendation_trim_execution_attempt BIGINT,
  recommendation_trim_execution_provenance_source TEXT,
  recommendation_trim_execution_provenance_source_id TEXT,
  recommendation_trim_execution_provenance_observed_at TIMESTAMPTZ,
  recommendation_trim_execution_template_version BIGINT,
  recommendation_smaller_model_object BOOLEAN,
  recommendation_smaller_model_origin_id TEXT,
  recommendation_smaller_model_source TEXT,
  recommendation_smaller_model_status TEXT,
  recommendation_smaller_model_timestamp TIMESTAMPTZ,
  recommendation_smaller_model_observed_at TIMESTAMPTZ,
  recommendation_smaller_model_sequence BIGINT,
  recommendation_smaller_model_source_sequence BIGINT,
  recommendation_smaller_model_payload_ref TEXT,
  recommendation_smaller_model_attempt BIGINT,
  recommendation_smaller_model_provenance_source TEXT,
  recommendation_smaller_model_provenance_source_id TEXT,
  recommendation_smaller_model_provenance_observed_at TIMESTAMPTZ,
  recommendation_smaller_model_template_version BIGINT,
  recommendation_allow_domains_object BOOLEAN,
  recommendation_allow_domains_origin_id TEXT,
  recommendation_allow_domains_source TEXT,
  recommendation_allow_domains_status TEXT,
  recommendation_allow_domains_timestamp TIMESTAMPTZ,
  recommendation_allow_domains_observed_at TIMESTAMPTZ,
  recommendation_allow_domains_sequence BIGINT,
  recommendation_allow_domains_source_sequence BIGINT,
  recommendation_allow_domains_payload_ref TEXT,
  recommendation_allow_domains_attempt BIGINT,
  recommendation_allow_domains_provenance_source TEXT,
  recommendation_allow_domains_provenance_source_id TEXT,
  recommendation_allow_domains_provenance_observed_at TIMESTAMPTZ,
  recommendation_allow_domains_template_version BIGINT,
  recommendation_deterministic_object BOOLEAN,
  recommendation_deterministic_origin_id TEXT,
  recommendation_deterministic_source TEXT,
  recommendation_deterministic_status TEXT,
  recommendation_deterministic_timestamp TIMESTAMPTZ,
  recommendation_deterministic_observed_at TIMESTAMPTZ,
  recommendation_deterministic_sequence BIGINT,
  recommendation_deterministic_source_sequence BIGINT,
  recommendation_deterministic_payload_ref TEXT,
  recommendation_deterministic_attempt BIGINT,
  recommendation_deterministic_provenance_source TEXT,
  recommendation_deterministic_provenance_source_id TEXT,
  recommendation_deterministic_provenance_observed_at TIMESTAMPTZ,
  recommendation_deterministic_template_version BIGINT,
  recommendation_stronger_evidence_object BOOLEAN,
  recommendation_stronger_evidence_origin_id TEXT,
  recommendation_stronger_evidence_source TEXT,
  recommendation_stronger_evidence_status TEXT,
  recommendation_stronger_evidence_timestamp TIMESTAMPTZ,
  recommendation_stronger_evidence_observed_at TIMESTAMPTZ,
  recommendation_stronger_evidence_sequence BIGINT,
  recommendation_stronger_evidence_source_sequence BIGINT,
  recommendation_stronger_evidence_payload_ref TEXT,
  recommendation_stronger_evidence_attempt BIGINT,
  recommendation_stronger_evidence_provenance_source TEXT,
  recommendation_stronger_evidence_provenance_source_id TEXT,
  recommendation_stronger_evidence_provenance_observed_at TIMESTAMPTZ,
  recommendation_stronger_evidence_template_version BIGINT,
  recommendation_monitor_object BOOLEAN,
  recommendation_monitor_origin_id TEXT,
  recommendation_monitor_source TEXT,
  recommendation_monitor_status TEXT,
  recommendation_monitor_timestamp TIMESTAMPTZ,
  recommendation_monitor_observed_at TIMESTAMPTZ,
  recommendation_monitor_sequence BIGINT,
  recommendation_monitor_source_sequence BIGINT,
  recommendation_monitor_payload_ref TEXT,
  recommendation_monitor_attempt BIGINT,
  recommendation_monitor_provenance_source TEXT,
  recommendation_monitor_provenance_source_id TEXT,
  recommendation_monitor_provenance_observed_at TIMESTAMPTZ,
  recommendation_monitor_template_version BIGINT,
  observability_network_friction_object BOOLEAN,
  observability_network_friction_origin_id TEXT,
  observability_network_friction_source TEXT,
  observability_network_friction_status TEXT,
  observability_network_friction_timestamp TIMESTAMPTZ,
  observability_network_friction_observed_at TIMESTAMPTZ,
  observability_network_friction_sequence BIGINT,
  observability_network_friction_source_sequence BIGINT,
  observability_network_friction_payload_ref TEXT,
  observability_network_friction_attempt BIGINT,
  observability_network_friction_provenance_source TEXT,
  observability_network_friction_provenance_source_id TEXT,
  observability_network_friction_provenance_observed_at TIMESTAMPTZ,
  observability_network_friction_template_version BIGINT,
  observability_exploratory_object BOOLEAN,
  observability_exploratory_origin_id TEXT,
  observability_exploratory_source TEXT,
  observability_exploratory_status TEXT,
  observability_exploratory_timestamp TIMESTAMPTZ,
  observability_exploratory_observed_at TIMESTAMPTZ,
  observability_exploratory_sequence BIGINT,
  observability_exploratory_source_sequence BIGINT,
  observability_exploratory_payload_ref TEXT,
  observability_exploratory_attempt BIGINT,
  observability_exploratory_provenance_source TEXT,
  observability_exploratory_provenance_source_id TEXT,
  observability_exploratory_provenance_observed_at TIMESTAMPTZ,
  observability_exploratory_template_version BIGINT,
  observability_anomaly_object BOOLEAN,
  observability_anomaly_origin_id TEXT,
  observability_anomaly_source TEXT,
  observability_anomaly_status TEXT,
  observability_anomaly_timestamp TIMESTAMPTZ,
  observability_anomaly_observed_at TIMESTAMPTZ,
  observability_anomaly_sequence BIGINT,
  observability_anomaly_source_sequence BIGINT,
  observability_anomaly_payload_ref TEXT,
  observability_anomaly_attempt BIGINT,
  observability_anomaly_provenance_source TEXT,
  observability_anomaly_provenance_source_id TEXT,
  observability_anomaly_provenance_observed_at TIMESTAMPTZ,
  observability_anomaly_template_version BIGINT,
  action_minutes NUMERIC,
  admission_reason TEXT,
  admission_status TEXT,
  agent_id TEXT,
  agent_runtime TEXT,
  agent_version TEXT,
  aic_total NUMERIC,
  attempt BIGINT,
  branch TEXT,
  cache_read_tokens BIGINT,
  cache_write_tokens BIGINT,
  classification TEXT,
  completed_at TIMESTAMPTZ,
  conclusion TEXT,
  created_at TIMESTAMPTZ,
  duration TEXT,
  engine TEXT,
  engine_id TEXT,
  engine_version TEXT,
  error_count BIGINT,
  event TEXT,
  failure_detail TEXT,
  failure_job TEXT,
  failure_kind TEXT,
  failure_log TEXT,
  failure_message TEXT,
  failure_step TEXT,
  firewall_version TEXT,
  gateway_version TEXT,
  gh_aw_version TEXT,
  github_api_calls BIGINT,
  github_run_id TEXT,
  head_sha TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  input_tokens BIGINT,
  model_id TEXT,
  organization_link_object BOOLEAN,
  organization_link_relation TEXT,
  organization_link_href TEXT,
  organization_link_label TEXT,
  output_tokens BIGINT,
  owner TEXT,
  reasoning_tokens BIGINT,
  repository TEXT,
  repository_id TEXT,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  requested_model TEXT,
  resolved_model TEXT,
  resource TEXT,
  resource_reset_at TIMESTAMPTZ,
  resource_wait_hours NUMERIC,
  rollout_mode TEXT,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,
  safe_items_count BIGINT,
  started_at TIMESTAMPTZ,
  status TEXT,
  target_repository TEXT,
  terminal_outcome TEXT,
  terminal_outcome_detail TEXT,
  title TEXT,
  updated_at TIMESTAMPTZ,
  workflow_id TEXT,
  workflow_link_object BOOLEAN,
  workflow_link_relation TEXT,
  workflow_link_href TEXT,
  workflow_link_label TEXT,
  workflow_path TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 355),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (repository_id IS NOT NULL AND repository_id <> ''),
  FOREIGN KEY (namespace, repository_id) REFERENCES repositories(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS runs_repository_id ON runs (namespace, repository_id, ordinal);

CREATE INDEX IF NOT EXISTS runs_workflow_id ON runs (namespace, workflow_id, ordinal);

CREATE INDEX IF NOT EXISTS runs_identity ON runs (namespace, id);

CREATE TABLE IF NOT EXISTS audits (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  attempt BIGINT,
  sequence BIGINT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  grader TEXT,
  grader_name TEXT,
  grader_source TEXT,
  value NUMERIC,
  unit TEXT,
  direction TEXT,
  message TEXT,
  error TEXT,
  baseline_value NUMERIC,
  delta_from_baseline NUMERIC,
  eval_id TEXT,
  answer TEXT,
  safe_output_type TEXT,
  github_entity_type TEXT,
  accepted_at TIMESTAMPTZ,
  activation_source TEXT,
  actor TEXT,
  cost_grain TEXT,
  evidence_confidence NUMERIC,
  evidence_state TEXT,
  aic NUMERIC,
  assignment_run_id TEXT,
  cache_read_tokens BIGINT,
  cache_write_tokens BIGINT,
  claim_run_attempt BIGINT,
  claim_run_id TEXT,
  code TEXT,
  control_variant TEXT,
  correlation_id TEXT,
  decision TEXT,
  events_truncated BOOLEAN,
  evidence_window_end TIMESTAMPTZ,
  evidence_window_start TIMESTAMPTZ,
  experiment_id TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  implementation_change_id TEXT,
  implementation_completed_at TIMESTAMPTZ,
  implementation_pull_request_url TEXT,
  implementation_started_at TIMESTAMPTZ,
  input_tokens BIGINT,
  intervention_id TEXT,
  intervention_state TEXT,
  lifecycle_observation_id TEXT,
  linked_invocations BIGINT,
  measurement_state TEXT,
  missing_reason TEXT,
  name TEXT,
  observed_at TIMESTAMPTZ,
  opportunity_id TEXT,
  opportunity_kind TEXT,
  optimized_variant TEXT,
  optimizer_run_attempt BIGINT,
  optimizer_workflow_name TEXT,
  optimizer_workflow_path TEXT,
  output_tokens BIGINT,
  payload_ref TEXT,
  previous_intervention_state TEXT,
  previous_recommendation_disposition TEXT,
  proposed_savings_aic NUMERIC,
  reasoning_tokens BIGINT,
  recommendation_churn_count BIGINT,
  recommendation_churn_rate NUMERIC,
  recommendation_disposition TEXT,
  rejected_at TIMESTAMPTZ,
  run_id TEXT,
  source TEXT,
  source_sequence BIGINT,
  status TEXT,
  summary TEXT,
  superseded_at TIMESTAMPTZ,
  superseded_by_intervention_id TEXT,
  supersedes_intervention_id TEXT,
  target_organization TEXT,
  target_repository TEXT,
  target_workflow_path TEXT,
  timestamp TIMESTAMPTZ,
  tool_calls BIGINT,
  total_events BIGINT,
  total_tokens BIGINT,
  turns BIGINT,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 87),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS audits_run_id ON audits (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS audits_identity ON audits (namespace, id);

CREATE TABLE IF NOT EXISTS domains (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  correlation_id TEXT,
  decision TEXT,
  domain TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  request_count BIGINT,
  run_id TEXT,
  source TEXT,
  source_sequence BIGINT,
  status TEXT,
  summary TEXT,
  timestamp TIMESTAMPTZ,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 14),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS domains_run_id ON domains (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS domains_identity ON domains (namespace, id);

CREATE TABLE IF NOT EXISTS evals (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  direction TEXT,
  display_name TEXT,
  first_observed_at TIMESTAMPTZ,
  id TEXT NOT NULL CHECK (id <> ''),
  last_observed_at TIMESTAMPTZ,
  name TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  question TEXT,
  requested_model TEXT,
  role TEXT,
  source_eval_id TEXT,
  timestamp TIMESTAMPTZ,
  workflow_id TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 16),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS evals_workflow_id ON evals (namespace, workflow_id, ordinal);

CREATE TABLE IF NOT EXISTS experiments (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  campaign TEXT,
  candidate_variant TEXT,
  control_variant TEXT,
  decision TEXT,
  evidence_strength NUMERIC,
  first_observed_at TIMESTAMPTZ,
  id TEXT NOT NULL CHECK (id <> ''),
  last_observed_at TIMESTAMPTZ,
  name TEXT,
  normalized_effect NUMERIC,
  primary_metric TEXT,
  primary_source TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  readiness TEXT,
  state TEXT,
  timestamp TIMESTAMPTZ,
  workflow_id TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 20),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS experiments_workflow_id ON experiments (namespace, workflow_id, ordinal);

CREATE TABLE IF NOT EXISTS eval_observations (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  audit_id TEXT,
  audit_evidence_object BOOLEAN,
  audit_evidence_origin_id TEXT,
  audit_evidence_source TEXT,
  audit_evidence_status TEXT,
  audit_evidence_timestamp TIMESTAMPTZ,
  audit_evidence_observed_at TIMESTAMPTZ,
  audit_evidence_sequence BIGINT,
  audit_evidence_source_sequence BIGINT,
  audit_evidence_payload_ref TEXT,
  audit_evidence_attempt BIGINT,
  audit_evidence_provenance_source TEXT,
  audit_evidence_provenance_source_id TEXT,
  audit_evidence_provenance_observed_at TIMESTAMPTZ,
  audit_evidence_template_version BIGINT,
  direction TEXT,
  eval_id TEXT,
  eval_link TEXT,
  eval_result TEXT,
  exclusion_reason TEXT,
  experiment_id TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  included BOOLEAN,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  role TEXT,
  run_id TEXT,
  status TEXT,
  timestamp TIMESTAMPTZ,
  variant TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 32),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (eval_id IS NOT NULL AND eval_id <> ''),
  FOREIGN KEY (namespace, eval_id) REFERENCES evals(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (namespace, experiment_id) REFERENCES experiments(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS eval_observations_eval_id ON eval_observations (namespace, eval_id, ordinal);

CREATE INDEX IF NOT EXISTS eval_observations_experiment_id ON eval_observations (namespace, experiment_id, ordinal);

CREATE INDEX IF NOT EXISTS eval_observations_run_id ON eval_observations (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS eval_observations_identity ON eval_observations (namespace, id);

CREATE TABLE IF NOT EXISTS experiment_assignments (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  audit_id TEXT,
  artifact_link TEXT,
  campaign TEXT,
  exclusion_reason TEXT,
  experiment_id TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  included BOOLEAN,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  run_id TEXT,
  timestamp TIMESTAMPTZ,
  trace_link TEXT,
  variant TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 15),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (experiment_id IS NOT NULL AND experiment_id <> ''),
  FOREIGN KEY (namespace, experiment_id) REFERENCES experiments(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS experiment_assignments_experiment_id ON experiment_assignments (namespace, experiment_id, ordinal);

CREATE INDEX IF NOT EXISTS experiment_assignments_run_id ON experiment_assignments (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS experiment_assignments_identity ON experiment_assignments (namespace, id);

CREATE TABLE IF NOT EXISTS friction (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  aic NUMERIC,
  input_tokens BIGINT,
  output_tokens BIGINT,
  cache_read_tokens BIGINT,
  cache_write_tokens BIGINT,
  reasoning_tokens BIGINT,
  total_tokens BIGINT,
  turns BIGINT,
  tool_calls BIGINT,
  latency_ms NUMERIC,
  events_truncated BOOLEAN,
  linked_invocations BIGINT,
  total_events BIGINT,
  canonical_unit TEXT,
  correlation_id TEXT,
  cost_grain TEXT,
  counted_occurrences BIGINT,
  decision TEXT,
  derived BOOLEAN,
  evidence_confidence NUMERIC,
  evidence_state TEXT,
  friction_ratio NUMERIC,
  id TEXT NOT NULL CHECK (id <> ''),
  measurement_state TEXT,
  missing_reason TEXT,
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  run_id TEXT,
  source TEXT,
  source_sequence BIGINT,
  summary TEXT,
  suppressed_occurrences BIGINT,
  timestamp TIMESTAMPTZ,
  total_occurrences BIGINT,
  total_run_aic NUMERIC,
  type TEXT,
  unattributed_occurrences BIGINT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 37),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS friction_run_id ON friction (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS friction_identity ON friction (namespace, id);

CREATE TABLE IF NOT EXISTS graders (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  direction TEXT,
  display_name TEXT,
  first_observed_at TIMESTAMPTZ,
  id TEXT NOT NULL CHECK (id <> ''),
  last_observed_at TIMESTAMPTZ,
  name TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  role TEXT,
  source_grader_id TEXT,
  threshold NUMERIC,
  timestamp TIMESTAMPTZ,
  unit TEXT,
  workflow_id TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 16),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS graders_workflow_id ON graders (namespace, workflow_id, ordinal);

CREATE TABLE IF NOT EXISTS grader_observations (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  observed_name TEXT,
  observed_unit TEXT,
  observed_direction TEXT,
  grader_source TEXT,
  message TEXT,
  error TEXT,
  audit_evidence_object BOOLEAN,
  audit_evidence_origin_id TEXT,
  audit_evidence_source TEXT,
  audit_evidence_status TEXT,
  audit_evidence_timestamp TIMESTAMPTZ,
  audit_evidence_observed_at TIMESTAMPTZ,
  audit_evidence_sequence BIGINT,
  audit_evidence_source_sequence BIGINT,
  audit_evidence_payload_ref TEXT,
  audit_evidence_attempt BIGINT,
  audit_evidence_provenance_source TEXT,
  audit_evidence_provenance_source_id TEXT,
  audit_evidence_provenance_observed_at TIMESTAMPTZ,
  audit_evidence_template_version BIGINT,
  audit_id TEXT,
  baseline_value NUMERIC,
  delta_from_baseline NUMERIC,
  evaluator_digest TEXT,
  evidence_link TEXT,
  exclusion_reason TEXT,
  experiment_id TEXT,
  grader_id TEXT,
  grader_link TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  included BOOLEAN,
  maturity_status TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  role TEXT,
  run_id TEXT,
  status TEXT,
  timestamp TIMESTAMPTZ,
  value NUMERIC,
  variant TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 42),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  FOREIGN KEY (namespace, experiment_id) REFERENCES experiments(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (grader_id IS NOT NULL AND grader_id <> ''),
  FOREIGN KEY (namespace, grader_id) REFERENCES graders(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS grader_observations_experiment_id ON grader_observations (namespace, experiment_id, ordinal);

CREATE INDEX IF NOT EXISTS grader_observations_grader_id ON grader_observations (namespace, grader_id, ordinal);

CREATE INDEX IF NOT EXISTS grader_observations_run_id ON grader_observations (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS grader_observations_identity ON grader_observations (namespace, id);

CREATE TABLE IF NOT EXISTS issues (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  audit_evidence_object BOOLEAN,
  audit_evidence_origin_id TEXT,
  audit_evidence_source TEXT,
  audit_evidence_status TEXT,
  audit_evidence_timestamp TIMESTAMPTZ,
  audit_evidence_observed_at TIMESTAMPTZ,
  audit_evidence_sequence BIGINT,
  audit_evidence_source_sequence BIGINT,
  audit_evidence_payload_ref TEXT,
  audit_evidence_attempt BIGINT,
  audit_evidence_provenance_source TEXT,
  audit_evidence_provenance_source_id TEXT,
  audit_evidence_provenance_observed_at TIMESTAMPTZ,
  audit_evidence_template_version BIGINT,
  closed BOOLEAN,
  closed_at TIMESTAMPTZ,
  correlation_id TEXT,
  github_entity_type TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  is_pull_request BOOLEAN,
  name TEXT,
  number BIGINT,
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  run_id TEXT,
  safe_output_id TEXT,
  safe_output_type TEXT,
  safe_output_url TEXT,
  source TEXT,
  source_sequence BIGINT,
  state TEXT,
  state_reason TEXT,
  status TEXT,
  status_observed_at TIMESTAMPTZ,
  summary TEXT,
  timestamp TIMESTAMPTZ,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 37),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS issues_run_id ON issues (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS issues_identity ON issues (namespace, id);

CREATE TABLE IF NOT EXISTS operational_values (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  adoption_at TIMESTAMPTZ,
  baseline_value NUMERIC,
  campaign TEXT,
  delta_from_baseline NUMERIC,
  evaluation_mode TEXT,
  evaluator_digest TEXT,
  evidence_cutoff TIMESTAMPTZ,
  evidence_link TEXT,
  experiment TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  maturity_at TIMESTAMPTZ,
  maturity_status TEXT,
  observation_id TEXT,
  operational_case TEXT,
  operational_value_direction TEXT,
  operational_value_name TEXT,
  operational_value_role TEXT,
  operational_value_unit TEXT,
  repository_id TEXT,
  requested_evidence_at TIMESTAMPTZ,
  rollout_mode TEXT,
  rollup_denominator NUMERIC,
  rollup_numerator NUMERIC,
  run TEXT,
  run_attempt NUMERIC,
  run_link TEXT,
  timestamp TIMESTAMPTZ,
  value NUMERIC,
  value_id TEXT,
  workflow TEXT,
  workflow_link TEXT,
  workflow_name TEXT,
  workflow_slug TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 33),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (repository_id IS NOT NULL AND repository_id <> ''),
  FOREIGN KEY (namespace, repository_id) REFERENCES repositories(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS operational_values_repository_id ON operational_values (namespace, repository_id, ordinal);

CREATE TABLE IF NOT EXISTS outcome_performance (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  organization TEXT,
  repository TEXT,
  workflow TEXT,
  run TEXT,
  run_conclusion TEXT,
  rollout_mode TEXT,
  safe_output_kind TEXT,
  outcome_title TEXT,
  outcome_status TEXT,
  observed_at TIMESTAMPTZ,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 15),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS security_findings (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  organization TEXT,
  repository TEXT,
  workflow TEXT,
  run TEXT,
  observed_at TIMESTAMPTZ,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,
  rollout_mode TEXT,
  usable_verdict_percent NUMERIC,
  prompt_injection_detected BOOLEAN,
  secret_leak_detected BOOLEAN,
  malicious_patch_detected BOOLEAN,
  inspection_warning_count BIGINT,
  inspection_warning TEXT,
  smell_summary TEXT,
  job_status TEXT,
  job_conclusion TEXT,
  job_duration_seconds NUMERIC,
  runner TEXT,
  engine TEXT,
  requested_model TEXT,
  resolved_model TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 25),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS skills (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  activation_source TEXT,
  correlation_id TEXT,
  failed_count BIGINT,
  id TEXT NOT NULL CHECK (id <> ''),
  invocation_count BIGINT,
  name TEXT,
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  run_id TEXT,
  source TEXT,
  source_sequence BIGINT,
  status TEXT,
  summary TEXT,
  timestamp TIMESTAMPTZ,
  tool_type TEXT,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 16),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS skills_run_id ON skills (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS skills_identity ON skills (namespace, id);

CREATE TABLE IF NOT EXISTS tools (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  correlation_id TEXT,
  failed_count BIGINT,
  id TEXT NOT NULL CHECK (id <> ''),
  invocation_count BIGINT,
  latency_ms NUMERIC,
  mcp_protocol_version TEXT,
  mcp_server TEXT,
  mcp_server_version TEXT,
  mcp_tool TEXT,
  name TEXT,
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  request_bytes BIGINT,
  response_bytes BIGINT,
  run_id TEXT,
  source TEXT,
  source_sequence BIGINT,
  status TEXT,
  summary TEXT,
  timestamp TIMESTAMPTZ,
  tool_type TEXT,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 22),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS tools_run_id ON tools (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS tools_identity ON tools (namespace, id);

CREATE TABLE IF NOT EXISTS transactions (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  kind TEXT,
  created_at TIMESTAMPTZ,
  source_clock TIMESTAMPTZ,
  payload_scope TEXT,
  payload_hash TEXT,
  payload_etag TEXT,
  records BIGINT,
  committed_records BIGINT,
  raw_payload_records BIGINT,
  raw_runs BIGINT,
  agentic_run_records BIGINT,
  agentic_runs BIGINT,
  duplicate_raw_run_observations BIGINT,
  duplicate_agentic_run_observations BIGINT,
  unenriched_runs BIGINT,
  error TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 17),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_items (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  work_item_id TEXT,
  name TEXT,
  objective TEXT,
  organization TEXT,
  repository TEXT,
  workflow TEXT,
  workflow_name TEXT,
  workflow_icon TEXT,
  workflow_role TEXT,
  scope TEXT,
  domain TEXT,
  campaign TEXT,
  campaign_name TEXT,
  campaign_icon TEXT,
  work_type TEXT,
  lifecycle_state TEXT,
  phase TEXT,
  reason TEXT,
  reason_evidence_class TEXT,
  next_action TEXT,
  next_actor TEXT,
  safe_output_kind TEXT,
  waiting_on TEXT,
  waiting_since TIMESTAMPTZ,
  owner TEXT,
  consequence_tier TEXT,
  verification_state TEXT,
  outcome_state TEXT,
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  observed_at TIMESTAMPTZ,
  evidence_link_object BOOLEAN,
  evidence_link_relation TEXT,
  evidence_link_href TEXT,
  evidence_link_label TEXT,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 44),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);
