-- Generated from server/spec/storage.tsp. Do not edit.

-- Fresh database only. Opaque artifacts remain external.

-- Inventory normalization contract: f14c6e284504dd4b77d773b756dd862f321ca3f0ccc9e60a6646f55314cddd72

CREATE TABLE IF NOT EXISTS cao_contract (
  digest TEXT NOT NULL,
  PRIMARY KEY (digest)
);

CREATE TABLE IF NOT EXISTS cao_state (
  namespace TEXT NOT NULL,
  revision BIGINT NOT NULL,
  data_revision TEXT NOT NULL,
  evaluated_at TIMESTAMPTZ NOT NULL,
  schema_version BIGINT NOT NULL,
  PRIMARY KEY (namespace)
);

CREATE TABLE IF NOT EXISTS cao_quality (
  namespace TEXT NOT NULL,
  collection TEXT NOT NULL,
  row_count BIGINT NOT NULL,
  availability TEXT NOT NULL,
  completeness TEXT NOT NULL,
  freshness TEXT NOT NULL,
  as_of TIMESTAMPTZ,
  retrieved_at TIMESTAMPTZ,
  PRIMARY KEY (namespace, collection),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (collection IN ('$repositories','$workflows','$runs','$audits','$campaigns','$domains','$evals','$experiments','$evalObservations','$experimentAssignments','$friction','$graders','$graderObservations','$issues','$operationalValues','$outcomes','$security-findings','$skills','$toolIdentities','$tools','$toolCounters','$transactions','work-items')),
  CHECK (availability IN ('available','empty','unavailable')),
  CHECK (completeness IN ('complete','partial','unknown')),
  CHECK (freshness IN ('current','stale','unknown'))
);

CREATE TABLE IF NOT EXISTS cao_repository_lifecycle (
  namespace TEXT NOT NULL,
  id TEXT NOT NULL,
  owner TEXT NOT NULL,
  name TEXT NOT NULL,
  lifecycle TEXT NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (namespace, id),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (lifecycle IN ('active','archived','deleted'))
);

CREATE INDEX IF NOT EXISTS cao_repository_lifecycle_coordinate ON cao_repository_lifecycle (namespace, owner, name);

CREATE TABLE IF NOT EXISTS repositories (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  name TEXT,
  observed_at TIMESTAMPTZ,
  organization_link_object BOOLEAN,
  organization_link_relation TEXT,
  organization_link_href TEXT,
  organization_link_label TEXT,
  owner TEXT,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  rollout_mode TEXT,
  lifecycle TEXT,
  visibility TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 15),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS workflows (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  admission_reason TEXT,
  admission_status TEXT,
  campaign TEXT,
  campaign_ai_credit_allowance NUMERIC,
  campaign_icon TEXT,
  campaign_inventory_warnings BIGINT,
  campaign_name TEXT,
  campaign_readme_path TEXT,
  campaign_worker_count BIGINT,
  created_at TIMESTAMPTZ,
  external_link_object BOOLEAN,
  external_link_relation TEXT,
  external_link_href TEXT,
  external_link_label TEXT,
  gh_aw_current_version TEXT,
  gh_aw_update_state TEXT,
  gh_aw_version TEXT,
  gh_aw_version_label TEXT,
  github_id TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  inventory_ready BOOLEAN,
  max_ai_credits NUMERIC,
  name TEXT,
  observed_at TIMESTAMPTZ,
  organization_link_object BOOLEAN,
  organization_link_relation TEXT,
  organization_link_href TEXT,
  organization_link_label TEXT,
  path TEXT,
  registry_state TEXT,
  repository_id TEXT NOT NULL,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  role TEXT,
  rollout_mode TEXT,
  state TEXT,
  updated_at TIMESTAMPTZ,
  workflow_link_object BOOLEAN,
  workflow_link_relation TEXT,
  workflow_link_href TEXT,
  workflow_link_label TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 43),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (repository_id IS NOT NULL AND repository_id <> ''),
  FOREIGN KEY (namespace, repository_id) REFERENCES repositories(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS workflows_repository_id ON workflows (namespace, repository_id, ordinal);

CREATE TABLE IF NOT EXISTS runs (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  action_minutes NUMERIC,
  admission_reason TEXT,
  admission_status TEXT,
  agent_id TEXT,
  agent_runtime TEXT,
  agent_version TEXT,
  aic_total NUMERIC,
  attempt BIGINT,
  branch TEXT,
  cache_read_tokens BIGINT,
  cache_write_tokens BIGINT,
  classification TEXT,
  completed_at TIMESTAMPTZ,
  conclusion TEXT,
  created_at TIMESTAMPTZ,
  duration TEXT,
  engine TEXT,
  engine_id TEXT,
  engine_version TEXT,
  error_count BIGINT,
  event TEXT,
  failure_detail TEXT,
  failure_job TEXT,
  failure_kind TEXT,
  failure_log TEXT,
  failure_message TEXT,
  failure_step TEXT,
  firewall_version TEXT,
  gateway_version TEXT,
  gh_aw_version TEXT,
  github_api_calls BIGINT,
  github_run_id TEXT,
  head_sha TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  input_tokens BIGINT,
  model_id TEXT,
  organization_link_object BOOLEAN,
  organization_link_relation TEXT,
  organization_link_href TEXT,
  organization_link_label TEXT,
  output_tokens BIGINT,
  owner TEXT,
  reasoning_tokens BIGINT,
  repository TEXT,
  repository_id TEXT NOT NULL,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  requested_model TEXT,
  resolved_model TEXT,
  resource TEXT,
  resource_reset_at TIMESTAMPTZ,
  resource_wait_hours NUMERIC,
  rollout_mode TEXT,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,
  safe_items_count BIGINT,
  started_at TIMESTAMPTZ,
  status TEXT,
  target_repository TEXT,
  terminal_outcome TEXT,
  terminal_outcome_detail TEXT,
  title TEXT,
  tool_usage_revision TEXT,
  updated_at TIMESTAMPTZ,
  workflow_id TEXT NOT NULL,
  workflow_link_object BOOLEAN,
  workflow_link_relation TEXT,
  workflow_link_href TEXT,
  workflow_link_label TEXT,
  workflow_path TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 74),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (repository_id IS NOT NULL AND repository_id <> ''),
  FOREIGN KEY (namespace, repository_id) REFERENCES repositories(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS runs_repository_id ON runs (namespace, repository_id, ordinal);

CREATE INDEX IF NOT EXISTS runs_workflow_id ON runs (namespace, workflow_id, ordinal);

CREATE INDEX IF NOT EXISTS runs_identity ON runs (namespace, id);

CREATE TABLE IF NOT EXISTS audits (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  accepted_at TIMESTAMPTZ,
  activation_source TEXT,
  actor TEXT,
  cost_grain TEXT,
  evidence_confidence NUMERIC,
  evidence_state TEXT,
  aic NUMERIC,
  assignment_run_id TEXT,
  cache_read_tokens BIGINT,
  cache_write_tokens BIGINT,
  claim_run_attempt BIGINT,
  claim_run_id TEXT,
  code TEXT,
  control_variant TEXT,
  correlation_id TEXT,
  decision TEXT,
  events_truncated BOOLEAN,
  evidence_window_end TIMESTAMPTZ,
  evidence_window_start TIMESTAMPTZ,
  experiment_id TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  implementation_change_id TEXT,
  implementation_completed_at TIMESTAMPTZ,
  implementation_pull_request_url TEXT,
  implementation_started_at TIMESTAMPTZ,
  input_tokens BIGINT,
  intervention_id TEXT,
  intervention_state TEXT,
  lifecycle_observation_id TEXT,
  linked_invocations BIGINT,
  measurement_state TEXT,
  missing_reason TEXT,
  name TEXT,
  observed_at TIMESTAMPTZ,
  opportunity_id TEXT,
  opportunity_kind TEXT,
  optimized_variant TEXT,
  optimizer_run_attempt BIGINT,
  optimizer_workflow_name TEXT,
  optimizer_workflow_path TEXT,
  output_tokens BIGINT,
  payload_ref TEXT,
  previous_intervention_state TEXT,
  previous_recommendation_disposition TEXT,
  proposed_savings_aic NUMERIC,
  reasoning_tokens BIGINT,
  recommendation_churn_count BIGINT,
  recommendation_churn_rate NUMERIC,
  recommendation_disposition TEXT,
  rejected_at TIMESTAMPTZ,
  run_id TEXT NOT NULL,
  source TEXT,
  source_sequence BIGINT,
  status TEXT,
  summary TEXT,
  superseded_at TIMESTAMPTZ,
  superseded_by_intervention_id TEXT,
  supersedes_intervention_id TEXT,
  target_organization TEXT,
  target_repo TEXT,
  target_repository TEXT,
  target_workflow_path TEXT,
  timestamp TIMESTAMPTZ,
  tool_calls BIGINT,
  total_events BIGINT,
  total_tokens BIGINT,
  turns BIGINT,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 68),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS audits_run_id ON audits (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS audits_identity ON audits (namespace, id);

CREATE TABLE IF NOT EXISTS campaigns (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  ai_credit_allowance NUMERIC,
  campaign_link_object BOOLEAN,
  campaign_link_relation TEXT,
  campaign_link_href TEXT,
  campaign_link_label TEXT,
  current_version TEXT,
  description TEXT,
  enabled BOOLEAN,
  experimental BOOLEAN,
  icon TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  inventory_warnings BIGINT,
  max_repositories BIGINT,
  min_version TEXT,
  mode TEXT,
  monthly_ai_credit_budget NUMERIC,
  name TEXT,
  observed_at TIMESTAMPTZ,
  readme TEXT,
  readme_path TEXT,
  rollout_percent NUMERIC,
  slug TEXT,
  update_state TEXT,
  version TEXT,
  worker_count BIGINT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 25),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS domains (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  correlation_id TEXT,
  decision TEXT,
  domain TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  request_count BIGINT,
  run_id TEXT NOT NULL,
  source TEXT,
  source_sequence BIGINT,
  status TEXT,
  summary TEXT,
  timestamp TIMESTAMPTZ,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 14),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS domains_run_id ON domains (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS domains_identity ON domains (namespace, id);

CREATE TABLE IF NOT EXISTS evals (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  direction TEXT,
  display_name TEXT,
  first_observed_at TIMESTAMPTZ,
  id TEXT NOT NULL CHECK (id <> ''),
  last_observed_at TIMESTAMPTZ,
  name TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  question TEXT,
  requested_model TEXT,
  role TEXT,
  source_eval_id TEXT,
  timestamp TIMESTAMPTZ,
  workflow_id TEXT NOT NULL,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 16),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS evals_workflow_id ON evals (namespace, workflow_id, ordinal);

CREATE TABLE IF NOT EXISTS experiments (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  campaign TEXT,
  candidate_variant TEXT,
  control_variant TEXT,
  decision TEXT,
  evidence_strength NUMERIC,
  first_observed_at TIMESTAMPTZ,
  id TEXT NOT NULL CHECK (id <> ''),
  last_observed_at TIMESTAMPTZ,
  name TEXT,
  normalized_effect NUMERIC,
  primary_metric TEXT,
  primary_source TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  readiness TEXT,
  state TEXT,
  timestamp TIMESTAMPTZ,
  workflow_id TEXT NOT NULL,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 20),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS experiments_workflow_id ON experiments (namespace, workflow_id, ordinal);

CREATE TABLE IF NOT EXISTS eval_observations (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  direction TEXT,
  eval_id TEXT NOT NULL,
  eval_link TEXT,
  eval_result TEXT,
  exclusion_reason TEXT,
  experiment_id TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  included BOOLEAN,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  result_timestamp TIMESTAMPTZ,
  role TEXT,
  run_id TEXT NOT NULL,
  source_eval_id TEXT,
  status TEXT,
  timestamp TIMESTAMPTZ,
  variant TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 19),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (eval_id IS NOT NULL AND eval_id <> ''),
  FOREIGN KEY (namespace, eval_id) REFERENCES evals(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (namespace, experiment_id) REFERENCES experiments(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS eval_observations_eval_id ON eval_observations (namespace, eval_id, ordinal);

CREATE INDEX IF NOT EXISTS eval_observations_experiment_id ON eval_observations (namespace, experiment_id, ordinal);

CREATE INDEX IF NOT EXISTS eval_observations_run_id ON eval_observations (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS eval_observations_identity ON eval_observations (namespace, id);

CREATE TABLE IF NOT EXISTS experiment_assignments (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  artifact_link TEXT,
  campaign TEXT,
  exclusion_reason TEXT,
  experiment_id TEXT NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  included BOOLEAN,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  run_id TEXT NOT NULL,
  timestamp TIMESTAMPTZ,
  trace_link TEXT,
  variant TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 14),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (experiment_id IS NOT NULL AND experiment_id <> ''),
  FOREIGN KEY (namespace, experiment_id) REFERENCES experiments(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS experiment_assignments_experiment_id ON experiment_assignments (namespace, experiment_id, ordinal);

CREATE INDEX IF NOT EXISTS experiment_assignments_run_id ON experiment_assignments (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS experiment_assignments_identity ON experiment_assignments (namespace, id);

CREATE TABLE IF NOT EXISTS friction (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  aic NUMERIC,
  input_tokens BIGINT,
  output_tokens BIGINT,
  cache_read_tokens BIGINT,
  cache_write_tokens BIGINT,
  reasoning_tokens BIGINT,
  total_tokens BIGINT,
  turns BIGINT,
  tool_calls BIGINT,
  latency_ms NUMERIC,
  events_truncated BOOLEAN,
  linked_invocations BIGINT,
  total_events BIGINT,
  canonical_unit TEXT,
  correlation_id TEXT,
  cost_grain TEXT,
  counted_occurrences BIGINT,
  decision TEXT,
  derived BOOLEAN,
  evidence_confidence NUMERIC,
  evidence_state TEXT,
  friction_ratio NUMERIC,
  id TEXT NOT NULL CHECK (id <> ''),
  measurement_state TEXT,
  missing_reason TEXT,
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  run_id TEXT NOT NULL,
  source TEXT,
  source_sequence BIGINT,
  summary TEXT,
  suppressed_occurrences BIGINT,
  timestamp TIMESTAMPTZ,
  total_occurrences BIGINT,
  total_run_aic NUMERIC,
  type TEXT,
  unattributed_occurrences BIGINT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 37),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS friction_run_id ON friction (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS friction_identity ON friction (namespace, id);

CREATE TABLE IF NOT EXISTS graders (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  direction TEXT,
  display_name TEXT,
  first_observed_at TIMESTAMPTZ,
  id TEXT NOT NULL CHECK (id <> ''),
  last_observed_at TIMESTAMPTZ,
  name TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  role TEXT,
  source_grader_id TEXT,
  threshold NUMERIC,
  timestamp TIMESTAMPTZ,
  unit TEXT,
  workflow_id TEXT NOT NULL,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 16),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (workflow_id IS NOT NULL AND workflow_id <> ''),
  FOREIGN KEY (namespace, workflow_id) REFERENCES workflows(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS graders_workflow_id ON graders (namespace, workflow_id, ordinal);

CREATE TABLE IF NOT EXISTS grader_observations (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  audit_id TEXT,
  baseline_value NUMERIC,
  delta_from_baseline NUMERIC,
  evaluator_digest TEXT,
  evidence_link TEXT,
  exclusion_reason TEXT,
  experiment_id TEXT,
  grader_id TEXT NOT NULL,
  grader_link TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  included BOOLEAN,
  maturity_status TEXT,
  provenance_object BOOLEAN,
  provenance_source TEXT,
  provenance_source_id TEXT,
  provenance_observed_at TIMESTAMPTZ,
  result_timestamp TIMESTAMPTZ,
  role TEXT,
  run_id TEXT NOT NULL,
  source_grader_id TEXT,
  status TEXT,
  timestamp TIMESTAMPTZ,
  value NUMERIC,
  variant TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 24),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  FOREIGN KEY (namespace, experiment_id) REFERENCES experiments(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (grader_id IS NOT NULL AND grader_id <> ''),
  FOREIGN KEY (namespace, grader_id) REFERENCES graders(namespace, id) DEFERRABLE INITIALLY DEFERRED,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS grader_observations_experiment_id ON grader_observations (namespace, experiment_id, ordinal);

CREATE INDEX IF NOT EXISTS grader_observations_grader_id ON grader_observations (namespace, grader_id, ordinal);

CREATE INDEX IF NOT EXISTS grader_observations_run_id ON grader_observations (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS grader_observations_identity ON grader_observations (namespace, id);

CREATE TABLE IF NOT EXISTS issues (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  closed BOOLEAN,
  closed_at TIMESTAMPTZ,
  correlation_id TEXT,
  github_entity_type TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  is_pull_request BOOLEAN,
  name TEXT,
  number BIGINT,
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  run_id TEXT NOT NULL,
  safe_output_id TEXT,
  safe_output_type TEXT,
  safe_output_url TEXT,
  source TEXT,
  source_sequence BIGINT,
  state TEXT,
  state_reason TEXT,
  status TEXT,
  status_observed_at TIMESTAMPTZ,
  summary TEXT,
  timestamp TIMESTAMPTZ,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 23),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS issues_run_id ON issues (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS issues_identity ON issues (namespace, id);

CREATE TABLE IF NOT EXISTS operational_values (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  adoption_at TIMESTAMPTZ,
  baseline_value NUMERIC,
  campaign TEXT,
  delta_from_baseline NUMERIC,
  evaluation_mode TEXT,
  evaluator_digest TEXT,
  evidence_cutoff TIMESTAMPTZ,
  evidence_link TEXT,
  experiment TEXT,
  id TEXT NOT NULL CHECK (id <> ''),
  maturity_at TIMESTAMPTZ,
  maturity_status TEXT,
  observation_id TEXT,
  operational_case TEXT,
  operational_value_direction TEXT,
  operational_value_name TEXT,
  operational_value_role TEXT,
  operational_value_unit TEXT,
  repository_id TEXT NOT NULL,
  requested_evidence_at TIMESTAMPTZ,
  rollout_mode TEXT,
  rollup_denominator NUMERIC,
  rollup_numerator NUMERIC,
  run TEXT,
  run_attempt NUMERIC,
  run_link TEXT,
  timestamp TIMESTAMPTZ,
  value NUMERIC,
  value_id TEXT,
  workflow TEXT,
  workflow_link TEXT,
  workflow_name TEXT,
  workflow_slug TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 33),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (repository_id IS NOT NULL AND repository_id <> ''),
  FOREIGN KEY (namespace, repository_id) REFERENCES repositories(namespace, id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS operational_values_repository_id ON operational_values (namespace, repository_id, ordinal);

CREATE TABLE IF NOT EXISTS outcome_performance (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  organization TEXT,
  repository TEXT,
  workflow TEXT,
  run TEXT,
  run_conclusion TEXT,
  rollout_mode TEXT,
  safe_output_kind TEXT,
  outcome_title TEXT,
  outcome_status TEXT,
  observed_at TIMESTAMPTZ,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 15),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS security_findings (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  organization TEXT,
  repository TEXT,
  workflow TEXT,
  run TEXT,
  observed_at TIMESTAMPTZ,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,
  rollout_mode TEXT,
  usable_verdict_percent NUMERIC,
  prompt_injection_detected BOOLEAN,
  secret_leak_detected BOOLEAN,
  malicious_patch_detected BOOLEAN,
  inspection_warning_count BIGINT,
  inspection_warning TEXT,
  smell_summary TEXT,
  job_status TEXT,
  job_conclusion TEXT,
  job_duration_seconds NUMERIC,
  runner TEXT,
  engine TEXT,
  requested_model TEXT,
  resolved_model TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 25),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS skills (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  activation_source TEXT,
  correlation_id TEXT,
  failed_count BIGINT,
  id TEXT NOT NULL CHECK (id <> ''),
  invocation_count BIGINT,
  name TEXT,
  observed_at TIMESTAMPTZ,
  payload_ref TEXT,
  run_id TEXT NOT NULL,
  source TEXT,
  source_sequence BIGINT,
  status TEXT,
  summary TEXT,
  timestamp TIMESTAMPTZ,
  tool_type TEXT,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 16),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS skills_run_id ON skills (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS skills_identity ON skills (namespace, id);

CREATE TABLE IF NOT EXISTS tool_identities (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  mcp_protocol_version TEXT,
  mcp_server TEXT,
  mcp_server_version TEXT,
  mcp_tool TEXT,
  name TEXT,
  observed_at TIMESTAMPTZ NOT NULL,
  tool_type TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 8),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tools (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  evidence_revision TEXT NOT NULL,
  ambiguous_count BIGINT NOT NULL,
  call_count BIGINT NOT NULL,
  event_count BIGINT NOT NULL,
  failed_count BIGINT NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  incomplete_count BIGINT NOT NULL,
  latency_count BIGINT NOT NULL,
  latency_max NUMERIC,
  latency_min NUMERIC,
  latency_sum NUMERIC NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL,
  outcome_count BIGINT NOT NULL,
  request_bytes BIGINT NOT NULL,
  request_bytes_count BIGINT NOT NULL,
  response_bytes BIGINT NOT NULL,
  response_bytes_count BIGINT NOT NULL,
  run_id TEXT NOT NULL,
  sample_call_id TEXT,
  sample_outcome_id TEXT,
  source TEXT NOT NULL,
  success_count BIGINT NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL,
  last_timestamp TIMESTAMPTZ NOT NULL,
  tool_id TEXT NOT NULL,
  unknown_outcome_count BIGINT NOT NULL,
  unmatched_count BIGINT NOT NULL,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 27),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  UNIQUE (namespace, run_id, tool_id, source, run_at),
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED,
  CHECK (tool_id IS NOT NULL AND tool_id <> ''),
  FOREIGN KEY (namespace, tool_id) REFERENCES tool_identities(namespace, id) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS tools_run_id ON tools (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS tools_tool_id ON tools (namespace, tool_id, ordinal);

CREATE TABLE IF NOT EXISTS tool_counters (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  evidence_revision TEXT NOT NULL,
  event_count BIGINT NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  timestamp TIMESTAMPTZ NOT NULL,
  last_timestamp TIMESTAMPTZ NOT NULL,
  observed_at TIMESTAMPTZ NOT NULL,
  request_bytes BIGINT NOT NULL,
  request_bytes_count BIGINT NOT NULL,
  response_bytes BIGINT NOT NULL,
  response_bytes_count BIGINT NOT NULL,
  run_id TEXT NOT NULL,
  usage_id TEXT NOT NULL,
  status TEXT,
  type TEXT,
  run_at TIMESTAMPTZ NOT NULL,

  PRIMARY KEY (namespace, id, run_at),
  UNIQUE (namespace, ordinal, run_at),
  CHECK (bit_length(present_fields) = 14),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE,
  CHECK (run_id IS NOT NULL AND run_id <> ''),
  FOREIGN KEY (namespace, run_id, run_at) REFERENCES runs(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED,
  CHECK (usage_id IS NOT NULL AND usage_id <> ''),
  FOREIGN KEY (namespace, usage_id, run_at) REFERENCES tools(namespace, id, run_at) DEFERRABLE INITIALLY DEFERRED
) PARTITION BY RANGE (run_at);

CREATE INDEX IF NOT EXISTS tool_counters_run_id ON tool_counters (namespace, run_id, ordinal);

CREATE INDEX IF NOT EXISTS tool_counters_usage_id ON tool_counters (namespace, usage_id, ordinal);

CREATE TABLE IF NOT EXISTS transactions (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  kind TEXT,
  created_at TIMESTAMPTZ,
  payload_scope TEXT,
  payload_hash TEXT,
  payload_etag TEXT,
  records BIGINT,
  committed_records BIGINT,
  raw_payload_records BIGINT,
  raw_runs BIGINT,
  agentic_run_records BIGINT,
  agentic_runs BIGINT,
  duplicate_raw_run_observations BIGINT,
  duplicate_agentic_run_observations BIGINT,
  unenriched_runs BIGINT,
  error TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 16),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_items (
  namespace TEXT NOT NULL,
  ordinal BIGINT NOT NULL CHECK (ordinal >= 0),
  present_fields BIT VARYING NOT NULL,
  id TEXT NOT NULL CHECK (id <> ''),
  work_item_id TEXT,
  name TEXT,
  objective TEXT,
  organization TEXT,
  repository TEXT,
  workflow TEXT,
  workflow_name TEXT,
  workflow_icon TEXT,
  workflow_role TEXT,
  scope TEXT,
  domain TEXT,
  campaign TEXT,
  campaign_name TEXT,
  campaign_icon TEXT,
  work_type TEXT,
  lifecycle_state TEXT,
  phase TEXT,
  reason TEXT,
  reason_evidence_class TEXT,
  next_action TEXT,
  next_actor TEXT,
  safe_output_kind TEXT,
  waiting_on TEXT,
  waiting_since TIMESTAMPTZ,
  owner TEXT,
  consequence_tier TEXT,
  verification_state TEXT,
  outcome_state TEXT,
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  observed_at TIMESTAMPTZ,
  evidence_link_object BOOLEAN,
  evidence_link_relation TEXT,
  evidence_link_href TEXT,
  evidence_link_label TEXT,
  repository_link_object BOOLEAN,
  repository_link_relation TEXT,
  repository_link_href TEXT,
  repository_link_label TEXT,
  run_link_object BOOLEAN,
  run_link_relation TEXT,
  run_link_href TEXT,
  run_link_label TEXT,

  PRIMARY KEY (namespace, id),
  UNIQUE (namespace, ordinal),
  CHECK (bit_length(present_fields) = 44),
  FOREIGN KEY (namespace) REFERENCES cao_state(namespace) ON DELETE CASCADE
);
