// Code generated from server/spec/storage.tsp. DO NOT EDIT.

package postgresx

var entityTables = map[string]entityTable{
	"$repositories": {name: "repositories", runtime: false, canonical: true, partitioned: false, columns: []entityColumn{
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "organizationLink", name: "organization_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "organizationLink.relation", name: "organization_link_relation", kind: "", sql: "TEXT"},
		{field: "organizationLink.href", name: "organization_link_href", kind: "", sql: "TEXT"},
		{field: "organizationLink.label", name: "organization_link_label", kind: "", sql: "TEXT"},
		{field: "owner", name: "owner", kind: "", sql: "TEXT"},
		{field: "repositoryLink", name: "repository_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "repositoryLink.relation", name: "repository_link_relation", kind: "", sql: "TEXT"},
		{field: "repositoryLink.href", name: "repository_link_href", kind: "", sql: "TEXT"},
		{field: "repositoryLink.label", name: "repository_link_label", kind: "", sql: "TEXT"},
		{field: "rolloutMode", name: "rollout_mode", kind: "", sql: "TEXT"},
		{field: "visibility", name: "visibility", kind: "", sql: "TEXT"},
	}},
	"$workflows": {name: "workflows", runtime: false, canonical: true, partitioned: false, columns: []entityColumn{
		{field: "admissionReason", name: "admission_reason", kind: "", sql: "TEXT"},
		{field: "admissionStatus", name: "admission_status", kind: "", sql: "TEXT"},
		{field: "campaign", name: "campaign", kind: "", sql: "TEXT"},
		{field: "campaignAiCreditAllowance", name: "campaign_ai_credit_allowance", kind: "numeric", sql: "NUMERIC"},
		{field: "campaignIcon", name: "campaign_icon", kind: "", sql: "TEXT"},
		{field: "campaignInventoryWarnings", name: "campaign_inventory_warnings", kind: "numeric", sql: "BIGINT"},
		{field: "campaignName", name: "campaign_name", kind: "", sql: "TEXT"},
		{field: "campaignReadmePath", name: "campaign_readme_path", kind: "", sql: "TEXT"},
		{field: "campaignWorkerCount", name: "campaign_worker_count", kind: "numeric", sql: "BIGINT"},
		{field: "createdAt", name: "created_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "externalLink", name: "external_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "externalLink.relation", name: "external_link_relation", kind: "", sql: "TEXT"},
		{field: "externalLink.href", name: "external_link_href", kind: "", sql: "TEXT"},
		{field: "externalLink.label", name: "external_link_label", kind: "", sql: "TEXT"},
		{field: "ghAwCurrentVersion", name: "gh_aw_current_version", kind: "", sql: "TEXT"},
		{field: "ghAwUpdateState", name: "gh_aw_update_state", kind: "", sql: "TEXT"},
		{field: "ghAwVersion", name: "gh_aw_version", kind: "", sql: "TEXT"},
		{field: "ghAwVersionLabel", name: "gh_aw_version_label", kind: "", sql: "TEXT"},
		{field: "githubId", name: "github_id", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "inventoryReady", name: "inventory_ready", kind: "boolean", sql: "BOOLEAN"},
		{field: "maxAiCredits", name: "max_ai_credits", kind: "numeric", sql: "NUMERIC"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "organizationLink", name: "organization_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "organizationLink.relation", name: "organization_link_relation", kind: "", sql: "TEXT"},
		{field: "organizationLink.href", name: "organization_link_href", kind: "", sql: "TEXT"},
		{field: "organizationLink.label", name: "organization_link_label", kind: "", sql: "TEXT"},
		{field: "path", name: "path", kind: "", sql: "TEXT"},
		{field: "registryState", name: "registry_state", kind: "", sql: "TEXT"},
		{field: "repositoryId", name: "repository_id", kind: "", sql: "TEXT"},
		{field: "repositoryLink", name: "repository_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "repositoryLink.relation", name: "repository_link_relation", kind: "", sql: "TEXT"},
		{field: "repositoryLink.href", name: "repository_link_href", kind: "", sql: "TEXT"},
		{field: "repositoryLink.label", name: "repository_link_label", kind: "", sql: "TEXT"},
		{field: "role", name: "role", kind: "", sql: "TEXT"},
		{field: "rolloutMode", name: "rollout_mode", kind: "", sql: "TEXT"},
		{field: "state", name: "state", kind: "", sql: "TEXT"},
		{field: "updatedAt", name: "updated_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "workflowLink", name: "workflow_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "workflowLink.relation", name: "workflow_link_relation", kind: "", sql: "TEXT"},
		{field: "workflowLink.href", name: "workflow_link_href", kind: "", sql: "TEXT"},
		{field: "workflowLink.label", name: "workflow_link_label", kind: "", sql: "TEXT"},
	}},
	"$runs": {name: "runs", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "actionMinutes", name: "action_minutes", kind: "numeric", sql: "NUMERIC"},
		{field: "admissionReason", name: "admission_reason", kind: "", sql: "TEXT"},
		{field: "admissionStatus", name: "admission_status", kind: "", sql: "TEXT"},
		{field: "agentId", name: "agent_id", kind: "", sql: "TEXT"},
		{field: "agentRuntime", name: "agent_runtime", kind: "", sql: "TEXT"},
		{field: "agentVersion", name: "agent_version", kind: "", sql: "TEXT"},
		{field: "aicTotal", name: "aic_total", kind: "numeric", sql: "NUMERIC"},
		{field: "attempt", name: "attempt", kind: "numeric", sql: "BIGINT"},
		{field: "branch", name: "branch", kind: "", sql: "TEXT"},
		{field: "cacheReadTokens", name: "cache_read_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "cacheWriteTokens", name: "cache_write_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "classification", name: "classification", kind: "", sql: "TEXT"},
		{field: "completedAt", name: "completed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "conclusion", name: "conclusion", kind: "", sql: "TEXT"},
		{field: "createdAt", name: "created_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "duration", name: "duration", kind: "", sql: "TEXT"},
		{field: "engine", name: "engine", kind: "", sql: "TEXT"},
		{field: "engineId", name: "engine_id", kind: "", sql: "TEXT"},
		{field: "engineVersion", name: "engine_version", kind: "", sql: "TEXT"},
		{field: "errorCount", name: "error_count", kind: "numeric", sql: "BIGINT"},
		{field: "event", name: "event", kind: "", sql: "TEXT"},
		{field: "failureDetail", name: "failure_detail", kind: "", sql: "TEXT"},
		{field: "failureJob", name: "failure_job", kind: "", sql: "TEXT"},
		{field: "failureKind", name: "failure_kind", kind: "", sql: "TEXT"},
		{field: "failureLog", name: "failure_log", kind: "", sql: "TEXT"},
		{field: "failureMessage", name: "failure_message", kind: "", sql: "TEXT"},
		{field: "failureStep", name: "failure_step", kind: "", sql: "TEXT"},
		{field: "firewallVersion", name: "firewall_version", kind: "", sql: "TEXT"},
		{field: "gatewayVersion", name: "gateway_version", kind: "", sql: "TEXT"},
		{field: "ghAwVersion", name: "gh_aw_version", kind: "", sql: "TEXT"},
		{field: "githubApiCalls", name: "github_api_calls", kind: "numeric", sql: "BIGINT"},
		{field: "githubRunId", name: "github_run_id", kind: "", sql: "TEXT"},
		{field: "headSha", name: "head_sha", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "inputTokens", name: "input_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "modelId", name: "model_id", kind: "", sql: "TEXT"},
		{field: "organizationLink", name: "organization_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "organizationLink.relation", name: "organization_link_relation", kind: "", sql: "TEXT"},
		{field: "organizationLink.href", name: "organization_link_href", kind: "", sql: "TEXT"},
		{field: "organizationLink.label", name: "organization_link_label", kind: "", sql: "TEXT"},
		{field: "outputTokens", name: "output_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "owner", name: "owner", kind: "", sql: "TEXT"},
		{field: "reasoningTokens", name: "reasoning_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "repository", name: "repository", kind: "", sql: "TEXT"},
		{field: "repositoryId", name: "repository_id", kind: "", sql: "TEXT"},
		{field: "repositoryLink", name: "repository_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "repositoryLink.relation", name: "repository_link_relation", kind: "", sql: "TEXT"},
		{field: "repositoryLink.href", name: "repository_link_href", kind: "", sql: "TEXT"},
		{field: "repositoryLink.label", name: "repository_link_label", kind: "", sql: "TEXT"},
		{field: "requestedModel", name: "requested_model", kind: "", sql: "TEXT"},
		{field: "resolvedModel", name: "resolved_model", kind: "", sql: "TEXT"},
		{field: "resource", name: "resource", kind: "", sql: "TEXT"},
		{field: "resourceResetAt", name: "resource_reset_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "resourceWaitHours", name: "resource_wait_hours", kind: "numeric", sql: "NUMERIC"},
		{field: "rolloutMode", name: "rollout_mode", kind: "", sql: "TEXT"},
		{field: "runLink", name: "run_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "runLink.relation", name: "run_link_relation", kind: "", sql: "TEXT"},
		{field: "runLink.href", name: "run_link_href", kind: "", sql: "TEXT"},
		{field: "runLink.label", name: "run_link_label", kind: "", sql: "TEXT"},
		{field: "safeItemsCount", name: "safe_items_count", kind: "numeric", sql: "BIGINT"},
		{field: "startedAt", name: "started_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "targetRepository", name: "target_repository", kind: "", sql: "TEXT"},
		{field: "terminalOutcome", name: "terminal_outcome", kind: "", sql: "TEXT"},
		{field: "terminalOutcomeDetail", name: "terminal_outcome_detail", kind: "", sql: "TEXT"},
		{field: "title", name: "title", kind: "", sql: "TEXT"},
		{field: "updatedAt", name: "updated_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "workflowId", name: "workflow_id", kind: "", sql: "TEXT"},
		{field: "workflowLink", name: "workflow_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "workflowLink.relation", name: "workflow_link_relation", kind: "", sql: "TEXT"},
		{field: "workflowLink.href", name: "workflow_link_href", kind: "", sql: "TEXT"},
		{field: "workflowLink.label", name: "workflow_link_label", kind: "", sql: "TEXT"},
		{field: "workflowPath", name: "workflow_path", kind: "", sql: "TEXT"},
	}},
	"$audits": {name: "audits", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "acceptedAt", name: "accepted_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "activationSource", name: "activation_source", kind: "", sql: "TEXT"},
		{field: "actor", name: "actor", kind: "", sql: "TEXT"},
		{field: "costGrain", name: "cost_grain", kind: "", sql: "TEXT"},
		{field: "evidenceConfidence", name: "evidence_confidence", kind: "numeric", sql: "NUMERIC"},
		{field: "evidenceState", name: "evidence_state", kind: "", sql: "TEXT"},
		{field: "aic", name: "aic", kind: "numeric", sql: "NUMERIC"},
		{field: "assignmentRunId", name: "assignment_run_id", kind: "", sql: "TEXT"},
		{field: "cacheReadTokens", name: "cache_read_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "cacheWriteTokens", name: "cache_write_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "claimRunAttempt", name: "claim_run_attempt", kind: "numeric", sql: "BIGINT"},
		{field: "claimRunId", name: "claim_run_id", kind: "", sql: "TEXT"},
		{field: "code", name: "code", kind: "", sql: "TEXT"},
		{field: "controlVariant", name: "control_variant", kind: "", sql: "TEXT"},
		{field: "correlationId", name: "correlation_id", kind: "", sql: "TEXT"},
		{field: "decision", name: "decision", kind: "", sql: "TEXT"},
		{field: "eventsTruncated", name: "events_truncated", kind: "boolean", sql: "BOOLEAN"},
		{field: "evidenceWindowEnd", name: "evidence_window_end", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "evidenceWindowStart", name: "evidence_window_start", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "experimentId", name: "experiment_id", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "implementationChangeId", name: "implementation_change_id", kind: "", sql: "TEXT"},
		{field: "implementationCompletedAt", name: "implementation_completed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "implementationPullRequestUrl", name: "implementation_pull_request_url", kind: "", sql: "TEXT"},
		{field: "implementationStartedAt", name: "implementation_started_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "inputTokens", name: "input_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "interventionId", name: "intervention_id", kind: "", sql: "TEXT"},
		{field: "interventionState", name: "intervention_state", kind: "", sql: "TEXT"},
		{field: "lifecycleObservationId", name: "lifecycle_observation_id", kind: "", sql: "TEXT"},
		{field: "linkedInvocations", name: "linked_invocations", kind: "numeric", sql: "BIGINT"},
		{field: "measurementState", name: "measurement_state", kind: "", sql: "TEXT"},
		{field: "missingReason", name: "missing_reason", kind: "", sql: "TEXT"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "opportunityId", name: "opportunity_id", kind: "", sql: "TEXT"},
		{field: "opportunityKind", name: "opportunity_kind", kind: "", sql: "TEXT"},
		{field: "optimizedVariant", name: "optimized_variant", kind: "", sql: "TEXT"},
		{field: "optimizerRunAttempt", name: "optimizer_run_attempt", kind: "numeric", sql: "BIGINT"},
		{field: "optimizerWorkflowName", name: "optimizer_workflow_name", kind: "", sql: "TEXT"},
		{field: "optimizerWorkflowPath", name: "optimizer_workflow_path", kind: "", sql: "TEXT"},
		{field: "outputTokens", name: "output_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "payloadRef", name: "payload_ref", kind: "", sql: "TEXT"},
		{field: "previousInterventionState", name: "previous_intervention_state", kind: "", sql: "TEXT"},
		{field: "previousRecommendationDisposition", name: "previous_recommendation_disposition", kind: "", sql: "TEXT"},
		{field: "proposedSavingsAic", name: "proposed_savings_aic", kind: "numeric", sql: "NUMERIC"},
		{field: "reasoningTokens", name: "reasoning_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "recommendationChurnCount", name: "recommendation_churn_count", kind: "numeric", sql: "BIGINT"},
		{field: "recommendationChurnRate", name: "recommendation_churn_rate", kind: "numeric", sql: "NUMERIC"},
		{field: "recommendationDisposition", name: "recommendation_disposition", kind: "", sql: "TEXT"},
		{field: "rejectedAt", name: "rejected_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "source", name: "source", kind: "", sql: "TEXT"},
		{field: "sourceSequence", name: "source_sequence", kind: "numeric", sql: "BIGINT"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "summary", name: "summary", kind: "", sql: "TEXT"},
		{field: "supersededAt", name: "superseded_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "supersededByInterventionId", name: "superseded_by_intervention_id", kind: "", sql: "TEXT"},
		{field: "supersedesInterventionId", name: "supersedes_intervention_id", kind: "", sql: "TEXT"},
		{field: "targetOrganization", name: "target_organization", kind: "", sql: "TEXT"},
		{field: "targetRepo", name: "target_repo", kind: "", sql: "TEXT"},
		{field: "targetRepository", name: "target_repository", kind: "", sql: "TEXT"},
		{field: "targetWorkflowPath", name: "target_workflow_path", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "toolCalls", name: "tool_calls", kind: "numeric", sql: "BIGINT"},
		{field: "totalEvents", name: "total_events", kind: "numeric", sql: "BIGINT"},
		{field: "totalTokens", name: "total_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "turns", name: "turns", kind: "numeric", sql: "BIGINT"},
		{field: "type", name: "type", kind: "", sql: "TEXT"},
	}},
	"$campaigns": {name: "campaigns", runtime: false, canonical: true, partitioned: false, columns: []entityColumn{
		{field: "aiCreditAllowance", name: "ai_credit_allowance", kind: "numeric", sql: "NUMERIC"},
		{field: "campaignLink", name: "campaign_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "campaignLink.relation", name: "campaign_link_relation", kind: "", sql: "TEXT"},
		{field: "campaignLink.href", name: "campaign_link_href", kind: "", sql: "TEXT"},
		{field: "campaignLink.label", name: "campaign_link_label", kind: "", sql: "TEXT"},
		{field: "currentVersion", name: "current_version", kind: "", sql: "TEXT"},
		{field: "description", name: "description", kind: "", sql: "TEXT"},
		{field: "enabled", name: "enabled", kind: "boolean", sql: "BOOLEAN"},
		{field: "experimental", name: "experimental", kind: "boolean", sql: "BOOLEAN"},
		{field: "icon", name: "icon", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "inventoryWarnings", name: "inventory_warnings", kind: "numeric", sql: "BIGINT"},
		{field: "maxRepositories", name: "max_repositories", kind: "numeric", sql: "BIGINT"},
		{field: "minVersion", name: "min_version", kind: "", sql: "TEXT"},
		{field: "mode", name: "mode", kind: "", sql: "TEXT"},
		{field: "monthlyAiCreditBudget", name: "monthly_ai_credit_budget", kind: "numeric", sql: "NUMERIC"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "readme", name: "readme", kind: "", sql: "TEXT"},
		{field: "readmePath", name: "readme_path", kind: "", sql: "TEXT"},
		{field: "rolloutPercent", name: "rollout_percent", kind: "numeric", sql: "NUMERIC"},
		{field: "slug", name: "slug", kind: "", sql: "TEXT"},
		{field: "updateState", name: "update_state", kind: "", sql: "TEXT"},
		{field: "version", name: "version", kind: "", sql: "TEXT"},
		{field: "workerCount", name: "worker_count", kind: "numeric", sql: "BIGINT"},
	}},
	"collection-health": {name: "collection_health", runtime: true, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "configured", name: "configured", kind: "boolean", sql: "BOOLEAN"},
		{field: "health", name: "health", kind: "", sql: "TEXT"},
		{field: "queue-depth", name: "queue_depth", kind: "numeric", sql: "BIGINT"},
		{field: "pending-tasks", name: "pending_tasks", kind: "numeric", sql: "BIGINT"},
		{field: "oldest-pending-age", name: "oldest_pending_age", kind: "", sql: "TEXT"},
		{field: "dead-letters", name: "dead_letters", kind: "numeric", sql: "BIGINT"},
		{field: "backfill", name: "backfill", kind: "", sql: "TEXT"},
		{field: "backfill-failures", name: "backfill_failures", kind: "numeric", sql: "BIGINT"},
		{field: "backfill-queued-run-tasks", name: "backfill_queued_run_tasks", kind: "numeric", sql: "BIGINT"},
		{field: "webhook-load", name: "webhook_load", kind: "numeric", sql: "BIGINT"},
		{field: "collection-load", name: "collection_load", kind: "numeric", sql: "BIGINT"},
		{field: "failure-load", name: "failure_load", kind: "numeric", sql: "BIGINT"},
		{field: "last-projected", name: "last_projected", kind: "", sql: "TEXT"},
		{field: "health-revision", name: "health_revision", kind: "numeric", sql: "BIGINT"},
		{field: "last-webhook-at", name: "last_webhook_at", kind: "", sql: "TEXT"},
		{field: "last-failure-at", name: "last_failure_at", kind: "", sql: "TEXT"},
		{field: "last-failure-code", name: "last_failure_code", kind: "", sql: "TEXT"},
		{field: "last-success-at", name: "last_success_at", kind: "", sql: "TEXT"},
		{field: "webhook-received", name: "webhook_received", kind: "numeric", sql: "BIGINT"},
		{field: "webhook-duplicate", name: "webhook_duplicate", kind: "numeric", sql: "BIGINT"},
		{field: "webhook-admission-failed", name: "webhook_admission_failed", kind: "numeric", sql: "BIGINT"},
		{field: "task-queued", name: "task_queued", kind: "numeric", sql: "BIGINT"},
		{field: "task-coalesced", name: "task_coalesced", kind: "numeric", sql: "BIGINT"},
		{field: "collection-succeeded", name: "collection_succeeded", kind: "numeric", sql: "BIGINT"},
		{field: "collection-failed", name: "collection_failed", kind: "numeric", sql: "BIGINT"},
		{field: "collection-retried", name: "collection_retried", kind: "numeric", sql: "BIGINT"},
		{field: "collection-dead-lettered", name: "collection_dead_lettered", kind: "numeric", sql: "BIGINT"},
	}},
	"$domains": {name: "domains", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "correlationId", name: "correlation_id", kind: "", sql: "TEXT"},
		{field: "decision", name: "decision", kind: "", sql: "TEXT"},
		{field: "domain", name: "domain", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "payloadRef", name: "payload_ref", kind: "", sql: "TEXT"},
		{field: "requestCount", name: "request_count", kind: "numeric", sql: "BIGINT"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "source", name: "source", kind: "", sql: "TEXT"},
		{field: "sourceSequence", name: "source_sequence", kind: "numeric", sql: "BIGINT"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "summary", name: "summary", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "type", name: "type", kind: "", sql: "TEXT"},
	}},
	"$evals": {name: "evals", runtime: false, canonical: true, partitioned: false, columns: []entityColumn{
		{field: "direction", name: "direction", kind: "", sql: "TEXT"},
		{field: "displayName", name: "display_name", kind: "", sql: "TEXT"},
		{field: "firstObservedAt", name: "first_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "lastObservedAt", name: "last_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "provenance", name: "provenance_object", kind: "object", sql: "BOOLEAN"},
		{field: "provenance.source", name: "provenance_source", kind: "", sql: "TEXT"},
		{field: "provenance.sourceId", name: "provenance_source_id", kind: "", sql: "TEXT"},
		{field: "provenance.observedAt", name: "provenance_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "question", name: "question", kind: "", sql: "TEXT"},
		{field: "requestedModel", name: "requested_model", kind: "", sql: "TEXT"},
		{field: "role", name: "role", kind: "", sql: "TEXT"},
		{field: "sourceEvalId", name: "source_eval_id", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "workflowId", name: "workflow_id", kind: "", sql: "TEXT"},
	}},
	"$experiments": {name: "experiments", runtime: false, canonical: true, partitioned: false, columns: []entityColumn{
		{field: "campaign", name: "campaign", kind: "", sql: "TEXT"},
		{field: "candidateVariant", name: "candidate_variant", kind: "", sql: "TEXT"},
		{field: "controlVariant", name: "control_variant", kind: "", sql: "TEXT"},
		{field: "decision", name: "decision", kind: "", sql: "TEXT"},
		{field: "evidenceStrength", name: "evidence_strength", kind: "numeric", sql: "NUMERIC"},
		{field: "firstObservedAt", name: "first_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "lastObservedAt", name: "last_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "normalizedEffect", name: "normalized_effect", kind: "numeric", sql: "NUMERIC"},
		{field: "primaryMetric", name: "primary_metric", kind: "", sql: "TEXT"},
		{field: "primarySource", name: "primary_source", kind: "", sql: "TEXT"},
		{field: "provenance", name: "provenance_object", kind: "object", sql: "BOOLEAN"},
		{field: "provenance.source", name: "provenance_source", kind: "", sql: "TEXT"},
		{field: "provenance.sourceId", name: "provenance_source_id", kind: "", sql: "TEXT"},
		{field: "provenance.observedAt", name: "provenance_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "readiness", name: "readiness", kind: "", sql: "TEXT"},
		{field: "state", name: "state", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "workflowId", name: "workflow_id", kind: "", sql: "TEXT"},
	}},
	"$evalObservations": {name: "eval_observations", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "direction", name: "direction", kind: "", sql: "TEXT"},
		{field: "evalId", name: "eval_id", kind: "", sql: "TEXT"},
		{field: "evalLink", name: "eval_link", kind: "", sql: "TEXT"},
		{field: "evalResult", name: "eval_result", kind: "", sql: "TEXT"},
		{field: "exclusionReason", name: "exclusion_reason", kind: "", sql: "TEXT"},
		{field: "experimentId", name: "experiment_id", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "included", name: "included", kind: "boolean", sql: "BOOLEAN"},
		{field: "provenance", name: "provenance_object", kind: "object", sql: "BOOLEAN"},
		{field: "provenance.source", name: "provenance_source", kind: "", sql: "TEXT"},
		{field: "provenance.sourceId", name: "provenance_source_id", kind: "", sql: "TEXT"},
		{field: "provenance.observedAt", name: "provenance_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "resultTimestamp", name: "result_timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "role", name: "role", kind: "", sql: "TEXT"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "sourceEvalId", name: "source_eval_id", kind: "", sql: "TEXT"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "variant", name: "variant", kind: "", sql: "TEXT"},
	}},
	"$experimentAssignments": {name: "experiment_assignments", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "artifactLink", name: "artifact_link", kind: "", sql: "TEXT"},
		{field: "campaign", name: "campaign", kind: "", sql: "TEXT"},
		{field: "exclusionReason", name: "exclusion_reason", kind: "", sql: "TEXT"},
		{field: "experimentId", name: "experiment_id", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "included", name: "included", kind: "boolean", sql: "BOOLEAN"},
		{field: "provenance", name: "provenance_object", kind: "object", sql: "BOOLEAN"},
		{field: "provenance.source", name: "provenance_source", kind: "", sql: "TEXT"},
		{field: "provenance.sourceId", name: "provenance_source_id", kind: "", sql: "TEXT"},
		{field: "provenance.observedAt", name: "provenance_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "traceLink", name: "trace_link", kind: "", sql: "TEXT"},
		{field: "variant", name: "variant", kind: "", sql: "TEXT"},
	}},
	"$friction": {name: "friction", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "aic", name: "aic", kind: "numeric", sql: "NUMERIC"},
		{field: "inputTokens", name: "input_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "outputTokens", name: "output_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "cacheReadTokens", name: "cache_read_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "cacheWriteTokens", name: "cache_write_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "reasoningTokens", name: "reasoning_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "totalTokens", name: "total_tokens", kind: "numeric", sql: "BIGINT"},
		{field: "turns", name: "turns", kind: "numeric", sql: "BIGINT"},
		{field: "toolCalls", name: "tool_calls", kind: "numeric", sql: "BIGINT"},
		{field: "latencyMs", name: "latency_ms", kind: "numeric", sql: "NUMERIC"},
		{field: "eventsTruncated", name: "events_truncated", kind: "boolean", sql: "BOOLEAN"},
		{field: "linkedInvocations", name: "linked_invocations", kind: "numeric", sql: "BIGINT"},
		{field: "totalEvents", name: "total_events", kind: "numeric", sql: "BIGINT"},
		{field: "canonicalUnit", name: "canonical_unit", kind: "", sql: "TEXT"},
		{field: "correlationId", name: "correlation_id", kind: "", sql: "TEXT"},
		{field: "costGrain", name: "cost_grain", kind: "", sql: "TEXT"},
		{field: "countedOccurrences", name: "counted_occurrences", kind: "numeric", sql: "BIGINT"},
		{field: "decision", name: "decision", kind: "", sql: "TEXT"},
		{field: "derived", name: "derived", kind: "boolean", sql: "BOOLEAN"},
		{field: "evidenceConfidence", name: "evidence_confidence", kind: "numeric", sql: "NUMERIC"},
		{field: "evidenceState", name: "evidence_state", kind: "", sql: "TEXT"},
		{field: "frictionRatio", name: "friction_ratio", kind: "numeric", sql: "NUMERIC"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "measurementState", name: "measurement_state", kind: "", sql: "TEXT"},
		{field: "missingReason", name: "missing_reason", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "payloadRef", name: "payload_ref", kind: "", sql: "TEXT"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "source", name: "source", kind: "", sql: "TEXT"},
		{field: "sourceSequence", name: "source_sequence", kind: "numeric", sql: "BIGINT"},
		{field: "summary", name: "summary", kind: "", sql: "TEXT"},
		{field: "suppressedOccurrences", name: "suppressed_occurrences", kind: "numeric", sql: "BIGINT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "totalOccurrences", name: "total_occurrences", kind: "numeric", sql: "BIGINT"},
		{field: "totalRunAic", name: "total_run_aic", kind: "numeric", sql: "NUMERIC"},
		{field: "type", name: "type", kind: "", sql: "TEXT"},
		{field: "unattributedOccurrences", name: "unattributed_occurrences", kind: "numeric", sql: "BIGINT"},
	}},
	"github-quota-usage": {name: "github_quota_usage", runtime: true, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "observed-at", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "scope", name: "scope", kind: "", sql: "TEXT"},
		{field: "bucket", name: "bucket", kind: "", sql: "TEXT"},
		{field: "app", name: "app", kind: "", sql: "TEXT"},
		{field: "installation", name: "installation", kind: "numeric", sql: "BIGINT"},
		{field: "resource", name: "resource", kind: "", sql: "TEXT"},
		{field: "buckets", name: "buckets", kind: "numeric", sql: "BIGINT"},
		{field: "limit", name: "limit", kind: "numeric", sql: "BIGINT"},
		{field: "used", name: "used", kind: "numeric", sql: "BIGINT"},
		{field: "reserved", name: "reserved", kind: "numeric", sql: "BIGINT"},
		{field: "usage-percent", name: "usage_percent", kind: "numeric", sql: "NUMERIC"},
	}},
	"$graders": {name: "graders", runtime: false, canonical: true, partitioned: false, columns: []entityColumn{
		{field: "direction", name: "direction", kind: "", sql: "TEXT"},
		{field: "displayName", name: "display_name", kind: "", sql: "TEXT"},
		{field: "firstObservedAt", name: "first_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "lastObservedAt", name: "last_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "provenance", name: "provenance_object", kind: "object", sql: "BOOLEAN"},
		{field: "provenance.source", name: "provenance_source", kind: "", sql: "TEXT"},
		{field: "provenance.sourceId", name: "provenance_source_id", kind: "", sql: "TEXT"},
		{field: "provenance.observedAt", name: "provenance_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "role", name: "role", kind: "", sql: "TEXT"},
		{field: "sourceGraderId", name: "source_grader_id", kind: "", sql: "TEXT"},
		{field: "threshold", name: "threshold", kind: "numeric", sql: "NUMERIC"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "unit", name: "unit", kind: "", sql: "TEXT"},
		{field: "workflowId", name: "workflow_id", kind: "", sql: "TEXT"},
	}},
	"$graderObservations": {name: "grader_observations", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "auditId", name: "audit_id", kind: "", sql: "TEXT"},
		{field: "baselineValue", name: "baseline_value", kind: "numeric", sql: "NUMERIC"},
		{field: "deltaFromBaseline", name: "delta_from_baseline", kind: "numeric", sql: "NUMERIC"},
		{field: "evaluatorDigest", name: "evaluator_digest", kind: "", sql: "TEXT"},
		{field: "evidenceLink", name: "evidence_link", kind: "", sql: "TEXT"},
		{field: "exclusionReason", name: "exclusion_reason", kind: "", sql: "TEXT"},
		{field: "experimentId", name: "experiment_id", kind: "", sql: "TEXT"},
		{field: "graderId", name: "grader_id", kind: "", sql: "TEXT"},
		{field: "graderLink", name: "grader_link", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "included", name: "included", kind: "boolean", sql: "BOOLEAN"},
		{field: "maturityStatus", name: "maturity_status", kind: "", sql: "TEXT"},
		{field: "provenance", name: "provenance_object", kind: "object", sql: "BOOLEAN"},
		{field: "provenance.source", name: "provenance_source", kind: "", sql: "TEXT"},
		{field: "provenance.sourceId", name: "provenance_source_id", kind: "", sql: "TEXT"},
		{field: "provenance.observedAt", name: "provenance_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "resultTimestamp", name: "result_timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "role", name: "role", kind: "", sql: "TEXT"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "sourceGraderId", name: "source_grader_id", kind: "", sql: "TEXT"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "value", name: "value", kind: "numeric", sql: "NUMERIC"},
		{field: "variant", name: "variant", kind: "", sql: "TEXT"},
	}},
	"$issues": {name: "issues", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "closed", name: "closed", kind: "boolean", sql: "BOOLEAN"},
		{field: "closedAt", name: "closed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "correlationId", name: "correlation_id", kind: "", sql: "TEXT"},
		{field: "githubEntityType", name: "github_entity_type", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "isPullRequest", name: "is_pull_request", kind: "boolean", sql: "BOOLEAN"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "number", name: "number", kind: "numeric", sql: "BIGINT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "payloadRef", name: "payload_ref", kind: "", sql: "TEXT"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "safeOutputId", name: "safe_output_id", kind: "", sql: "TEXT"},
		{field: "safeOutputType", name: "safe_output_type", kind: "", sql: "TEXT"},
		{field: "safeOutputUrl", name: "safe_output_url", kind: "", sql: "TEXT"},
		{field: "source", name: "source", kind: "", sql: "TEXT"},
		{field: "sourceSequence", name: "source_sequence", kind: "numeric", sql: "BIGINT"},
		{field: "state", name: "state", kind: "", sql: "TEXT"},
		{field: "stateReason", name: "state_reason", kind: "", sql: "TEXT"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "statusObservedAt", name: "status_observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "summary", name: "summary", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "type", name: "type", kind: "", sql: "TEXT"},
	}},
	"$marketplacePackages": {name: "marketplace_packages", runtime: true, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "addCommand", name: "add_command", kind: "", sql: "TEXT"},
		{field: "artwork", name: "artwork", kind: "", sql: "TEXT"},
		{field: "description", name: "description", kind: "", sql: "TEXT"},
		{field: "forks", name: "forks", kind: "numeric", sql: "BIGINT"},
		{field: "icon", name: "icon", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "path", name: "path", kind: "", sql: "TEXT"},
		{field: "publisher", name: "publisher", kind: "", sql: "TEXT"},
		{field: "readme", name: "readme", kind: "", sql: "TEXT"},
		{field: "readmePath", name: "readme_path", kind: "", sql: "TEXT"},
		{field: "ref", name: "ref", kind: "", sql: "TEXT"},
		{field: "registryId", name: "registry_id", kind: "", sql: "TEXT"},
		{field: "registryName", name: "registry_name", kind: "", sql: "TEXT"},
		{field: "registryPrecedence", name: "registry_precedence", kind: "numeric", sql: "BIGINT"},
		{field: "repository", name: "repository", kind: "", sql: "TEXT"},
		{field: "repositoryLink", name: "repository_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "repositoryLink.relation", name: "repository_link_relation", kind: "", sql: "TEXT"},
		{field: "repositoryLink.href", name: "repository_link_href", kind: "", sql: "TEXT"},
		{field: "repositoryLink.label", name: "repository_link_label", kind: "", sql: "TEXT"},
		{field: "resolvedCommit", name: "resolved_commit", kind: "", sql: "TEXT"},
		{field: "sourceCoordinate", name: "source_coordinate", kind: "", sql: "TEXT"},
		{field: "stars", name: "stars", kind: "numeric", sql: "BIGINT"},
		{field: "version", name: "version", kind: "", sql: "TEXT"},
	}},
	"$operationalValues": {name: "operational_values", runtime: false, canonical: true, partitioned: false, columns: []entityColumn{
		{field: "adoption-at", name: "adoption_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "baseline-value", name: "baseline_value", kind: "numeric", sql: "NUMERIC"},
		{field: "campaign", name: "campaign", kind: "", sql: "TEXT"},
		{field: "delta-from-baseline", name: "delta_from_baseline", kind: "numeric", sql: "NUMERIC"},
		{field: "evaluation-mode", name: "evaluation_mode", kind: "", sql: "TEXT"},
		{field: "evaluator-digest", name: "evaluator_digest", kind: "", sql: "TEXT"},
		{field: "evidence-cutoff", name: "evidence_cutoff", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "evidence-link", name: "evidence_link", kind: "", sql: "TEXT"},
		{field: "experiment", name: "experiment", kind: "", sql: "TEXT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "maturity-at", name: "maturity_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "maturity-status", name: "maturity_status", kind: "", sql: "TEXT"},
		{field: "observation-id", name: "observation_id", kind: "", sql: "TEXT"},
		{field: "operational-case", name: "operational_case", kind: "", sql: "TEXT"},
		{field: "operational-value-direction", name: "operational_value_direction", kind: "", sql: "TEXT"},
		{field: "operational-value-name", name: "operational_value_name", kind: "", sql: "TEXT"},
		{field: "operational-value-role", name: "operational_value_role", kind: "", sql: "TEXT"},
		{field: "operational-value-unit", name: "operational_value_unit", kind: "", sql: "TEXT"},
		{field: "repositoryId", name: "repository_id", kind: "", sql: "TEXT"},
		{field: "requested-evidence-at", name: "requested_evidence_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "rollout-mode", name: "rollout_mode", kind: "", sql: "TEXT"},
		{field: "rollup-denominator", name: "rollup_denominator", kind: "numeric", sql: "NUMERIC"},
		{field: "rollup-numerator", name: "rollup_numerator", kind: "numeric", sql: "NUMERIC"},
		{field: "run", name: "run", kind: "", sql: "TEXT"},
		{field: "run-attempt", name: "run_attempt", kind: "numeric", sql: "NUMERIC"},
		{field: "run-link", name: "run_link", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "value", name: "value", kind: "numeric", sql: "NUMERIC"},
		{field: "valueId", name: "value_id", kind: "", sql: "TEXT"},
		{field: "workflow", name: "workflow", kind: "", sql: "TEXT"},
		{field: "workflow-link", name: "workflow_link", kind: "", sql: "TEXT"},
		{field: "workflow-name", name: "workflow_name", kind: "", sql: "TEXT"},
		{field: "workflow-slug", name: "workflow_slug", kind: "", sql: "TEXT"},
	}},
	"$outcomes": {name: "outcome_performance", runtime: false, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "organization", name: "organization", kind: "", sql: "TEXT"},
		{field: "repository", name: "repository", kind: "", sql: "TEXT"},
		{field: "workflow", name: "workflow", kind: "", sql: "TEXT"},
		{field: "run", name: "run", kind: "", sql: "TEXT"},
		{field: "run-conclusion", name: "run_conclusion", kind: "", sql: "TEXT"},
		{field: "rollout-mode", name: "rollout_mode", kind: "", sql: "TEXT"},
		{field: "safe-output-kind", name: "safe_output_kind", kind: "", sql: "TEXT"},
		{field: "outcome-title", name: "outcome_title", kind: "", sql: "TEXT"},
		{field: "outcome-status", name: "outcome_status", kind: "", sql: "TEXT"},
		{field: "observed-at", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "run-link", name: "run_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "run-link.relation", name: "run_link_relation", kind: "", sql: "TEXT"},
		{field: "run-link.href", name: "run_link_href", kind: "", sql: "TEXT"},
		{field: "run-link.label", name: "run_link_label", kind: "", sql: "TEXT"},
	}},
	"$security-findings": {name: "security_findings", runtime: false, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "organization", name: "organization", kind: "", sql: "TEXT"},
		{field: "repository", name: "repository", kind: "", sql: "TEXT"},
		{field: "workflow", name: "workflow", kind: "", sql: "TEXT"},
		{field: "run", name: "run", kind: "", sql: "TEXT"},
		{field: "observed-at", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "run-link", name: "run_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "run-link.relation", name: "run_link_relation", kind: "", sql: "TEXT"},
		{field: "run-link.href", name: "run_link_href", kind: "", sql: "TEXT"},
		{field: "run-link.label", name: "run_link_label", kind: "", sql: "TEXT"},
		{field: "rollout-mode", name: "rollout_mode", kind: "", sql: "TEXT"},
		{field: "usable-verdict-percent", name: "usable_verdict_percent", kind: "numeric", sql: "NUMERIC"},
		{field: "prompt-injection-detected", name: "prompt_injection_detected", kind: "boolean", sql: "BOOLEAN"},
		{field: "secret-leak-detected", name: "secret_leak_detected", kind: "boolean", sql: "BOOLEAN"},
		{field: "malicious-patch-detected", name: "malicious_patch_detected", kind: "boolean", sql: "BOOLEAN"},
		{field: "inspection-warning-count", name: "inspection_warning_count", kind: "numeric", sql: "BIGINT"},
		{field: "inspection-warning", name: "inspection_warning", kind: "", sql: "TEXT"},
		{field: "smell-summary", name: "smell_summary", kind: "", sql: "TEXT"},
		{field: "job-status", name: "job_status", kind: "", sql: "TEXT"},
		{field: "job-conclusion", name: "job_conclusion", kind: "", sql: "TEXT"},
		{field: "job-duration-seconds", name: "job_duration_seconds", kind: "numeric", sql: "NUMERIC"},
		{field: "runner", name: "runner", kind: "", sql: "TEXT"},
		{field: "engine", name: "engine", kind: "", sql: "TEXT"},
		{field: "requested-model", name: "requested_model", kind: "", sql: "TEXT"},
		{field: "resolved-model", name: "resolved_model", kind: "", sql: "TEXT"},
	}},
	"simulation-days": {name: "simulation_days", runtime: true, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "day", name: "day", kind: "numeric", sql: "BIGINT"},
		{field: "date", name: "date", kind: "timestamp", sql: "TIMESTAMPTZ"},
	}},
	"$skills": {name: "skills", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "activationSource", name: "activation_source", kind: "", sql: "TEXT"},
		{field: "correlationId", name: "correlation_id", kind: "", sql: "TEXT"},
		{field: "failedCount", name: "failed_count", kind: "numeric", sql: "BIGINT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "invocationCount", name: "invocation_count", kind: "numeric", sql: "BIGINT"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "payloadRef", name: "payload_ref", kind: "", sql: "TEXT"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "source", name: "source", kind: "", sql: "TEXT"},
		{field: "sourceSequence", name: "source_sequence", kind: "numeric", sql: "BIGINT"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "summary", name: "summary", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "toolType", name: "tool_type", kind: "", sql: "TEXT"},
		{field: "type", name: "type", kind: "", sql: "TEXT"},
	}},
	"$tools": {name: "tools", runtime: false, canonical: true, partitioned: true, columns: []entityColumn{
		{field: "correlationId", name: "correlation_id", kind: "", sql: "TEXT"},
		{field: "failedCount", name: "failed_count", kind: "numeric", sql: "BIGINT"},
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "invocationCount", name: "invocation_count", kind: "numeric", sql: "BIGINT"},
		{field: "latencyMs", name: "latency_ms", kind: "numeric", sql: "NUMERIC"},
		{field: "mcpProtocolVersion", name: "mcp_protocol_version", kind: "", sql: "TEXT"},
		{field: "mcpServer", name: "mcp_server", kind: "", sql: "TEXT"},
		{field: "mcpServerVersion", name: "mcp_server_version", kind: "", sql: "TEXT"},
		{field: "mcpTool", name: "mcp_tool", kind: "", sql: "TEXT"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "observedAt", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "payloadRef", name: "payload_ref", kind: "", sql: "TEXT"},
		{field: "requestBytes", name: "request_bytes", kind: "numeric", sql: "BIGINT"},
		{field: "responseBytes", name: "response_bytes", kind: "numeric", sql: "BIGINT"},
		{field: "runId", name: "run_id", kind: "", sql: "TEXT"},
		{field: "source", name: "source", kind: "", sql: "TEXT"},
		{field: "sourceSequence", name: "source_sequence", kind: "numeric", sql: "BIGINT"},
		{field: "status", name: "status", kind: "", sql: "TEXT"},
		{field: "summary", name: "summary", kind: "", sql: "TEXT"},
		{field: "timestamp", name: "timestamp", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "toolType", name: "tool_type", kind: "", sql: "TEXT"},
		{field: "type", name: "type", kind: "", sql: "TEXT"},
	}},
	"$transactions": {name: "transactions", runtime: false, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "kind", name: "kind", kind: "", sql: "TEXT"},
		{field: "createdAt", name: "created_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "payloadScope", name: "payload_scope", kind: "", sql: "TEXT"},
		{field: "payloadHash", name: "payload_hash", kind: "", sql: "TEXT"},
		{field: "payloadEtag", name: "payload_etag", kind: "", sql: "TEXT"},
		{field: "records", name: "records", kind: "numeric", sql: "BIGINT"},
		{field: "committedRecords", name: "committed_records", kind: "numeric", sql: "BIGINT"},
		{field: "rawPayloadRecords", name: "raw_payload_records", kind: "numeric", sql: "BIGINT"},
		{field: "rawRuns", name: "raw_runs", kind: "numeric", sql: "BIGINT"},
		{field: "agenticRunRecords", name: "agentic_run_records", kind: "numeric", sql: "BIGINT"},
		{field: "agenticRuns", name: "agentic_runs", kind: "numeric", sql: "BIGINT"},
		{field: "duplicateRawRunObservations", name: "duplicate_raw_run_observations", kind: "numeric", sql: "BIGINT"},
		{field: "duplicateAgenticRunObservations", name: "duplicate_agentic_run_observations", kind: "numeric", sql: "BIGINT"},
		{field: "unenrichedRuns", name: "unenriched_runs", kind: "numeric", sql: "BIGINT"},
		{field: "error", name: "error", kind: "", sql: "TEXT"},
	}},
	"work-items": {name: "work_items", runtime: false, canonical: false, partitioned: false, columns: []entityColumn{
		{field: "id", name: "id", kind: "", sql: "TEXT"},
		{field: "work-item-id", name: "work_item_id", kind: "", sql: "TEXT"},
		{field: "name", name: "name", kind: "", sql: "TEXT"},
		{field: "objective", name: "objective", kind: "", sql: "TEXT"},
		{field: "organization", name: "organization", kind: "", sql: "TEXT"},
		{field: "repository", name: "repository", kind: "", sql: "TEXT"},
		{field: "workflow", name: "workflow", kind: "", sql: "TEXT"},
		{field: "workflow-name", name: "workflow_name", kind: "", sql: "TEXT"},
		{field: "workflow-icon", name: "workflow_icon", kind: "", sql: "TEXT"},
		{field: "workflow-role", name: "workflow_role", kind: "", sql: "TEXT"},
		{field: "scope", name: "scope", kind: "", sql: "TEXT"},
		{field: "domain", name: "domain", kind: "", sql: "TEXT"},
		{field: "campaign", name: "campaign", kind: "", sql: "TEXT"},
		{field: "campaign-name", name: "campaign_name", kind: "", sql: "TEXT"},
		{field: "campaign-icon", name: "campaign_icon", kind: "", sql: "TEXT"},
		{field: "work-type", name: "work_type", kind: "", sql: "TEXT"},
		{field: "lifecycle-state", name: "lifecycle_state", kind: "", sql: "TEXT"},
		{field: "phase", name: "phase", kind: "", sql: "TEXT"},
		{field: "reason", name: "reason", kind: "", sql: "TEXT"},
		{field: "reason-evidence-class", name: "reason_evidence_class", kind: "", sql: "TEXT"},
		{field: "next-action", name: "next_action", kind: "", sql: "TEXT"},
		{field: "next-actor", name: "next_actor", kind: "", sql: "TEXT"},
		{field: "safe-output-kind", name: "safe_output_kind", kind: "", sql: "TEXT"},
		{field: "waiting-on", name: "waiting_on", kind: "", sql: "TEXT"},
		{field: "waiting-since", name: "waiting_since", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "owner", name: "owner", kind: "", sql: "TEXT"},
		{field: "consequence-tier", name: "consequence_tier", kind: "", sql: "TEXT"},
		{field: "verification-state", name: "verification_state", kind: "", sql: "TEXT"},
		{field: "outcome-state", name: "outcome_state", kind: "", sql: "TEXT"},
		{field: "started-at", name: "started_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "ended-at", name: "ended_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "observed-at", name: "observed_at", kind: "timestamp", sql: "TIMESTAMPTZ"},
		{field: "evidence-link", name: "evidence_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "evidence-link.relation", name: "evidence_link_relation", kind: "", sql: "TEXT"},
		{field: "evidence-link.href", name: "evidence_link_href", kind: "", sql: "TEXT"},
		{field: "evidence-link.label", name: "evidence_link_label", kind: "", sql: "TEXT"},
		{field: "repository-link", name: "repository_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "repository-link.relation", name: "repository_link_relation", kind: "", sql: "TEXT"},
		{field: "repository-link.href", name: "repository_link_href", kind: "", sql: "TEXT"},
		{field: "repository-link.label", name: "repository_link_label", kind: "", sql: "TEXT"},
		{field: "run-link", name: "run_link_object", kind: "object", sql: "BOOLEAN"},
		{field: "run-link.relation", name: "run_link_relation", kind: "", sql: "TEXT"},
		{field: "run-link.href", name: "run_link_href", kind: "", sql: "TEXT"},
		{field: "run-link.label", name: "run_link_label", kind: "", sql: "TEXT"},
	}},
}

var inventoryBindings = map[string][]inventoryBinding{
	"campaigns": {
		{field: "name", inputs: []string{"campaign-name","package-name"}},
		{field: "description", inputs: []string{"campaign-description","package-description"}, defaultPresent: true, defaultValue: ""},
		{field: "icon", inputs: []string{"campaign-icon","package-icon"}, defaultPresent: true, defaultValue: "goal"},
		{field: "mode", inputs: []string{"campaign-mode","package-mode"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "enabled", inputs: []string{"campaign-enabled","package-enabled"}, defaultPresent: true, defaultValue: true, notEqualsPresent: true, notEquals: false},
		{field: "maxRepositories", inputs: []string{"campaign-max-repositories","package-max-repositories"}, defaultPresent: true, defaultValue: nil},
		{field: "rolloutPercent", inputs: []string{"campaign-rollout-percent","package-rollout-percent"}, defaultPresent: true, defaultValue: nil},
		{field: "monthlyAiCreditBudget", inputs: []string{"campaign-monthly-ai-credit-budget","package-monthly-ai-credit-budget"}, defaultPresent: true, defaultValue: nil},
		{field: "aiCreditAllowance", inputs: []string{"campaign-aic-allowance","package-aic-allowance"}, defaultPresent: true, defaultValue: nil},
		{field: "workerCount", inputs: []string{"campaign-worker-count","package-worker-count"}, defaultPresent: true, defaultValue: 0},
		{field: "inventoryWarnings", inputs: []string{"campaign-inventory-warnings","package-inventory-warnings"}, defaultPresent: true, defaultValue: 0},
		{field: "minVersion", inputs: []string{"campaign-min-version","package-min-version"}, defaultPresent: true, defaultValue: ""},
		{field: "version", inputs: []string{"campaign-version","package-version"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "currentVersion", inputs: []string{"campaign-current-version","package-current-version"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "updateState", inputs: []string{"campaign-update-state","package-update-state"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "experimental", inputs: []string{"campaign-experimental","package-experimental"}, equalsPresent: true, equals: true},
		{field: "readmePath", inputs: []string{"campaign-readme-path","package-readme-path"}, defaultPresent: true, defaultValue: ""},
		{field: "readme", inputs: []string{"campaign-readme","package-readme"}, defaultPresent: true, defaultValue: ""},
		{field: "campaignLink", inputs: []string{"campaign-link","package-link"}, defaultPresent: true, defaultValue: nil},
	},
	"repositories": {
		{field: "visibility", inputs: []string{"visibility"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "rolloutMode", inputs: []string{"rollout-mode"}},
		{field: "organizationLink", inputs: []string{"organization-link"}, defaultPresent: true, defaultValue: nil},
		{field: "repositoryLink", inputs: []string{"repository-link"}, defaultPresent: true, defaultValue: nil},
	},
	"workflows": {
		{field: "githubId", inputs: []string{"workflow-id"}, trim: true, omitEmpty: true},
		{field: "name", inputs: []string{"workflow-name","workflow"}, defaultPresent: true, defaultValue: ""},
		{field: "registryState", inputs: []string{"workflow-registry-state"}, trim: true, omitEmpty: true},
		{field: "createdAt", inputs: []string{"created-at"}, trim: true, omitEmpty: true},
		{field: "updatedAt", inputs: []string{"updated-at"}, trim: true, omitEmpty: true},
		{field: "ghAwVersion", inputs: []string{"gh-aw-version"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "ghAwCurrentVersion", inputs: []string{"gh-aw-current-version"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "ghAwVersionLabel", inputs: []string{"gh-aw-version-label"}},
		{field: "ghAwUpdateState", inputs: []string{"gh-aw-update-state"}, defaultPresent: true, defaultValue: "unknown"},
		{field: "workflowLink", inputs: []string{"workflow-link"}, defaultPresent: true, defaultValue: nil},
		{field: "organizationLink", inputs: []string{"organization-link"}, defaultPresent: true, defaultValue: nil},
		{field: "repositoryLink", inputs: []string{"repository-link"}, defaultPresent: true, defaultValue: nil},
		{field: "externalLink", inputs: []string{"external-link"}, defaultPresent: true, defaultValue: nil},
		{field: "campaignName", inputs: []string{"campaign-name","package-name"}},
		{field: "campaignIcon", inputs: []string{"campaign-icon","package-icon"}},
		{field: "role", inputs: []string{"workflow-role"}},
		{field: "rolloutMode", inputs: []string{"rollout-mode"}},
		{field: "maxAiCredits", inputs: []string{"max-ai-credits"}},
		{field: "admissionStatus", inputs: []string{"admission-status"}},
		{field: "admissionReason", inputs: []string{"admission-reason"}},
		{field: "campaignAiCreditAllowance", inputs: []string{"campaign-aic-allowance"}},
		{field: "campaignWorkerCount", inputs: []string{"campaign-worker-count"}},
		{field: "campaignInventoryWarnings", inputs: []string{"campaign-inventory-warnings"}},
		{field: "inventoryReady", inputs: []string{"inventory-ready"}},
	},
}
