import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import test from "node:test";

const executeFile = promisify(execFile);
const cao = path.resolve("activity/cao.mjs");
const releaseCommit = "1234567890abcdef1234567890abcdef12345678";
const installedCommit = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

test("cao init and update pin installed activity and dashboard workflows to release commits", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "cao-update-integration-"));
  const workflows = path.join(root, ".github", "workflows");
  const packages = path.join(root, ".github", "aw", "packages");
  const bin = path.join(root, "bin");
  const recordPath = path.join(packages, "root.json");
  const callsPath = path.join(root, "gh-calls.jsonl");
  try {
    await mkdir(workflows, { recursive: true });
    await mkdir(packages, { recursive: true });
    await mkdir(bin);
    const files = [];
    for (const workflow of ["activity", "dashboard"]) {
      const destination = `.github/workflows/cao-${workflow}.yml`;
      files.push({ destination, sha256: "old" });
      await writeFile(
        path.join(root, destination),
        `jobs:\n  build:\n    steps:\n      - name: Checkout trusted ${workflow} source\n        uses: actions/checkout@0123456789012345678901234567890123456789\n        with:\n          ref: \${{ github.workflow_sha }}\n          persist-credentials: false\n`,
      );
    }
    await writeFile(recordPath, JSON.stringify({
      schemaVersion: 1,
      package: "githubnext/gh-aw-cao",
      source: `githubnext/gh-aw-cao@${installedCommit}`,
      resolvedCommit: installedCommit,
      files,
    }));

    const gh = path.join(bin, "gh");
    await writeFile(gh, `#!/usr/bin/env node
const fs = require("node:fs");
const args = process.argv.slice(2);
fs.appendFileSync(process.env.GH_CALLS, JSON.stringify(args) + "\\n");
if (args[0] === "aw" && args[1] === "version") {
  console.log("gh aw version v0.89.17");
} else if (args[0] === "api" && args[1] === "--paginate") {
  console.log("v0.0.2-rc.1");
} else if (args[0] === "api" && args[1].includes("/releases/tags/")) {
  console.log("v0.0.2-rc.1");
} else if (args[0] === "aw" && args[1] === "update") {
  if (args.includes("--pre-releases")) process.exit(9);
  const record = JSON.parse(fs.readFileSync(process.env.CAO_RECORD, "utf8"));
  record.source = "githubnext/gh-aw-cao@v0.0.2-rc.1";
  record.resolvedCommit = "v0.0.2-rc.1";
  fs.writeFileSync(process.env.CAO_RECORD, JSON.stringify(record));
} else if (args[0] === "api" && args[1].includes("/commits/")) {
  console.log(process.env.CAO_RELEASE_COMMIT);
} else {
  process.exit(8);
}
`);
    await chmod(gh, 0o755);

    const environment = {
      ...process.env,
      PATH: `${bin}:${process.env.PATH}`,
      CAO_RECORD: recordPath,
      CAO_RELEASE_COMMIT: releaseCommit,
      GH_CALLS: callsPath,
    };
    await executeFile(process.execPath, [cao, "init"], {
      cwd: root,
      env: environment,
    });
    for (const workflow of ["activity", "dashboard"]) {
      const content = await readFile(path.join(workflows, `cao-${workflow}.yml`), "utf8");
      assert.match(content, new RegExp(`ref: ${installedCommit}`));
    }

    await executeFile(process.execPath, [cao, "update", "--pre-releases", "--force"], {
      cwd: root,
      env: environment,
    });

    for (const workflow of ["activity", "dashboard"]) {
      const content = await readFile(path.join(workflows, `cao-${workflow}.yml`), "utf8");
      assert.match(content, /# Managed by cao init\/update; do not edit this file directly\./);
      assert.match(content, /repository: githubnext\/gh-aw-cao/);
      assert.match(content, new RegExp(`ref: ${releaseCommit}`));
      assert.doesNotMatch(content, /github\.workflow_sha/);
    }
    const calls = (await readFile(callsPath, "utf8")).trim().split("\n").map(JSON.parse);
    assert.ok(calls.some((arguments_) => arguments_.includes(
      "select(.draft == false and true) | .tag_name",
    )));
    assert.ok(calls.some((arguments_) => arguments_[0] === "aw" && arguments_[1] === "update"));
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
