import assert from "node:assert/strict";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { checkGhAwVersionConsistency } from "../../scripts/check-gh-aw-versions.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

function write(rootDirectory, relativePath, contents) {
  const filePath = path.join(rootDirectory, relativePath);
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, contents);
}

test("repository gh-aw version declarations match the control policy", () => {
  const { expectedVersion, issues } = checkGhAwVersionConsistency(root);

  assert.match(expectedVersion, /^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/);
  assert.deepEqual(issues, []);
});

test("checker reports inconsistent manifests, locks, and documentation", () => {
  const fixtureRoot = path.join(tmpdir(), `cao-gh-aw-version-${process.pid}-${Date.now()}`);
  const files = [
    ".github/workflows/cao.json",
    ".github/workflows/activity.yml",
    ".github/workflows/example.lock.yml",
    "aw.yml",
    "campaign/aw.yml",
    "docs/configuration.md",
  ];

  try {
    write(fixtureRoot, ".github/workflows/cao.json", '{"version":1,"gh-aw-version":"v1.2.3"}\n');
    write(
      fixtureRoot,
      ".github/workflows/activity.yml",
      [
        "      - name: Install gh-aw",
        "        uses: github/gh-aw-actions/setup-cli@abc123 # v1.2.3",
        "        with:",
        "          version: v1.2.4",
        "",
      ].join("\n"),
    );
    write(fixtureRoot, "aw.yml", "name: Example\nmin-version: v1.2.3\n");
    write(fixtureRoot, "campaign/aw.yml", "name: Campaign\nmin-version: v1.2.2\n");
    write(
      fixtureRoot,
      ".github/workflows/example.lock.yml",
      [
        '# gh-aw-metadata: {"compiler_version":"v1.2.1"}',
        "# This file was automatically generated by gh-aw (v1.2.1). DO NOT EDIT.",
        "",
      ].join("\n"),
    );
    write(
      fixtureRoot,
      "docs/configuration.md",
      '```json\n{"gh-aw-version": "v1.2.0"}\n```\n',
    );

    const { issues } = checkGhAwVersionConsistency(fixtureRoot, files);

    assert.deepEqual(issues, [
      ".github/workflows/activity.yml:4: gh-aw version is v1.2.4, expected v1.2.3",
      ".github/workflows/example.lock.yml: compiler_version is \"v1.2.1\", expected v1.2.3",
      ".github/workflows/example.lock.yml: generated version is \"v1.2.1\", expected v1.2.3",
      "campaign/aw.yml: min-version is \"v1.2.2\", expected v1.2.3",
      "docs/configuration.md: documented gh-aw-version is v1.2.0, expected v1.2.3",
    ]);
  } finally {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
});
