import assert from "node:assert/strict";
import test from "node:test";
import { workflow } from "./workflow-contract.helpers.mjs";

test("hosted health is a four-hour, policy-gated SelfCare worker", () => {
  const orchestrator = workflow("self-care.md");
  const worker = workflow("self-care-hosted-health.md");

  assert.match(orchestrator, /self-care-hosted-health.*preceding four hours/);
  assert.match(orchestrator, /If any run history is unavailable or ambiguous, fail closed/);
  assert.match(orchestrator, /`review` permits only `self-care-hosted-health`/);
  assert.match(orchestrator, /Never dispatch a worker other than `self-care-hosted-health` in review mode/);
  assert.match(worker, /worker: hosted-health/);
  assert.match(worker, /cao_authorized == 'true'/);
  assert.match(worker, /precomputed `target_repo` is exactly `githubnext\/gh-aw-cao` and `safe_output_mode` is either `review` or `live`/);
  assert.match(worker, /In `review` mode, publish only through the configured review safe-output repository/);
  assert.doesNotMatch(worker, /inputs\.safe_output_mode \|\| 'review'\) == 'live'/);
  assert.doesNotMatch(worker, /^\s+schedule:/m);
});

test("hosted health reads CAO and OTEL through scoped MCP and replaces its report", () => {
  const worker = workflow("self-care-hosted-health.md");

  assert.match(worker, /url: https:\/\/cao\.githubnext\.com\/mcp/);
  assert.match(worker, /allowed: \[cao_catalog, cao_query\]/);
  assert.match(worker, /name: Verify hosted CAO health and MCP access/);
  assert.match(worker, /cao-hosted-smoke\.json/);
  assert.match(worker, /\/api\/readiness \/api\/health \/api\/v1\/health/);
  assert.match(worker, /--output \/dev\/null/);
  assert.match(worker, /MCP-Protocol-Version: 2026-07-28/);
  assert.match(worker, /provenance_mismatch/);
  assert.match(worker, /non_default_branch_provenance/);
  assert.match(worker, /non_default_branch_accepted/);
  assert.match(worker, /query_payload=.*campaign-runs.*limit\\":1/);
  assert.match(worker, /authorization_scope: "default_branch_only"/);
  assert.match(worker, /expected pre-merge review boundary/);
  assert.match(worker, /never recommend weakening default-branch OIDC provenance/);
  assert.match(worker, /do not call those endpoints directly from the agent/);
  assert.match(worker, /MCP runtime mismatch rather than missing credentials/);
  assert.match(worker, /url: \$\{\{ vars\.CAO_OTEL_MCP_URL \}\}/);
  assert.match(worker, /CAO_OTEL_MCP_READ_AUTHORIZATION/);
  assert.match(worker, /allowed: \[SearchSQL, StreamList, StreamSchema, GetLatestTraces\]/);
  assert.doesNotMatch(worker, /PrometheusRangeQuery/);
  assert.doesNotMatch(worker, /allowed: \[[^\]]*(tool_search|tools_call)/);
  assert.match(worker, /name: Verify OpenObserve MCP read access/);
  assert.match(worker, /openobserve-smoke\.json/);
  assert.match(worker, /backend_version: \$backend_version/);
  assert.match(worker, /mcp_endpoint_not_found/);
  assert.match(worker, /"\$openobserve_origin\/config"/);
  assert.match(worker, /"method":"tools\/list"/);
  assert.match(worker, /name: "SearchSQL"/);
  assert.match(worker, /name: "GetLatestTraces"/);
  assert.match(worker, /trace_stream: \$trace_stream/);
  assert.match(worker, /read_pull_requests: read/);
  assert.match(worker, /id-token: write/);
  assert.match(worker, /cache-memory:/);
  assert.match(worker, /rolling four-hour UTC window/);
  assert.match(worker, /exact format `YYYY-MM-DD HH:MM UTC CLASSIFICATION`/);
  assert.match(worker, /Call `create_issue` exactly once, only for the final report/);
  assert.match(worker, /Never use `create_issue` to test syntax, quoting, permissions, connectivity, placeholder content, or title\/body shape/);
  assert.match(worker, /Do not probe the safe-output CLI or invoke its help command/);
  assert.match(worker, /stable instrument names `go\.memory\.allocated`.*`go\.memory\.used`.*`go\.goroutine\.count`/);
  assert.match(worker, /never recommend deprecated `process\.runtime\.go\.\*` names/);
  assert.match(worker, /stable runtime instrumentation does not emit GC-pause duration/);
  assert.match(worker, /close-older-issues: true/);
  assert.match(worker, /deduplicate-by-title: true/);
  assert.match(worker, /If the OTEL MCP server, smoke result, or query capabilities are unavailable/);
  assert.match(worker, /Never infer that either is absent by inspecting environment variables/);
  assert.match(worker, /only a smoke reason of `missing_configuration` establishes that condition/);
  assert.match(worker, /Recommend provisioning the Actions variable or secret only for `missing_configuration`/);
  assert.match(worker, /do not recommend replacing it/);
  assert.match(worker, /do not assume Prometheus-compatible query access/);
  assert.match(worker, /Do not use `tool_search`, `tools_call`, or any mutation-capable OpenObserve tool/);
  assert.doesNotMatch(worker, /bash: \[[^\]]*curl/);
  assert.doesNotMatch(worker, /^\s+(contents|actions|issues|pull-requests): write$/m);
});
