export const policyMatrix = Object.freeze({
  configuredModes: ["review", "live"],
  selectedModes: ["review", "live"],
  manualReviewRepos: ["", "acme/manual-review"],
  rolloutPercents: [10, 100],
  maxReposValues: [1, 10, 1000],
  packageEnabledValues: [true, false],
  totalRepositories: 25,
});

export const userFacingScenarios = Object.freeze([
  {
    group: "Scheduled modes",
    name: "Scheduled review uses control repository",
    inputs: {
      eventName: "schedule",
      configuredMode: "review",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 10,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/control-plane",
      effectiveMaxRepos: 10,
      dispatchAllowed: true,
    },
  },
  {
    group: "Scheduled modes",
    name: "Scheduled review at 10 percent",
    inputs: {
      eventName: "schedule",
      configuredMode: "review",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 10,
      maxRepos: 1000,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/control-plane",
      effectiveMaxRepos: 3,
      dispatchAllowed: true,
    },
  },
  {
    group: "Scheduled modes",
    name: "Scheduled live at 100 percent",
    inputs: {
      eventName: "schedule",
      configuredMode: "live",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 1000,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 25,
      dispatchAllowed: true,
    },
  },
  {
    group: "Scheduled modes",
    name: "Scheduled live at 10 percent",
    inputs: {
      eventName: "schedule",
      configuredMode: "live",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 10,
      maxRepos: 1000,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 3,
      dispatchAllowed: true,
    },
  },
  {
    group: "Rollout limits",
    name: "Absolute cap is stricter than 10 percent",
    inputs: {
      eventName: "schedule",
      configuredMode: "live",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 10,
      maxRepos: 1,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 1,
      dispatchAllowed: true,
    },
  },
  {
    group: "Manual runs",
    name: "Manual review overrides scheduled live",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "live",
      manualMode: "review",
      manualReviewRepo: "acme/manual-review",
      rolloutPercent: 100,
      maxRepos: 1,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/manual-review",
      effectiveMaxRepos: 1,
      dispatchAllowed: true,
    },
  },
  {
    group: "Review routing",
    name: "Manual review defaults to control repository",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "live",
      manualMode: "review",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 1,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/control-plane",
      effectiveMaxRepos: 1,
      dispatchAllowed: true,
    },
  },
  {
    group: "Review routing",
    name: "Manual destination overrides control repository",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "review",
      manualReviewRepo: "acme/manual-review",
      rolloutPercent: 100,
      maxRepos: 1,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/manual-review",
      effectiveMaxRepos: 1,
      dispatchAllowed: true,
    },
  },
  {
    group: "Rollout limits",
    name: "Manual live at 10 percent",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "live",
      manualReviewRepo: "",
      rolloutPercent: 10,
      maxRepos: 10,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 3,
      dispatchAllowed: true,
    },
  },
  {
    group: "Rollout limits",
    name: "Manual live with absolute cap",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "live",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 10,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 10,
      dispatchAllowed: true,
    },
  },
  {
    group: "Manual runs",
    name: "Manual live runs while schedules are configured review",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "live",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 1000,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 25,
      dispatchAllowed: true,
    },
  },
  {
    group: "Manual runs",
    name: "Manual review runs while schedules are configured review",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "review",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 10,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/control-plane",
      effectiveMaxRepos: 10,
      dispatchAllowed: true,
    },
  },
  {
    group: "Review routing",
    name: "Scheduled review defaults to control repository",
    inputs: {
      eventName: "schedule",
      configuredMode: "review",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 1,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/control-plane",
      effectiveMaxRepos: 1,
      dispatchAllowed: true,
    },
  },
  {
    group: "Review routing",
    name: "Manual live ignores manual destination",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "live",
      manualReviewRepo: "acme/manual-review",
      rolloutPercent: 100,
      maxRepos: 1,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 1,
      dispatchAllowed: true,
    },
  },
  {
    group: "Rollout limits",
    name: "Manual live at 10 percent with bounded high cap",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "live",
      manualReviewRepo: "",
      rolloutPercent: 10,
      maxRepos: 1000,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 3,
      dispatchAllowed: true,
    },
  },
  {
    group: "Rollout limits",
    name: "Manual review at 10 percent with bounded high cap",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "live",
      manualMode: "review",
      manualReviewRepo: "",
      rolloutPercent: 10,
      maxRepos: 1000,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/control-plane",
      effectiveMaxRepos: 3,
      dispatchAllowed: true,
    },
  },
  {
    group: "Rollout limits",
    name: "Absolute cap of 1 wins at 100 percent",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "live",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 1,
    },
    expected: {
      safeOutputMode: "live",
      safeOutputRepo: "",
      effectiveMaxRepos: 1,
      dispatchAllowed: true,
    },
  },
  {
    group: "Rollout limits",
    name: "Absolute cap of 10 wins at 100 percent review",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "live",
      manualMode: "review",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 10,
    },
    expected: {
      safeOutputMode: "review",
      safeOutputRepo: "acme/control-plane",
      effectiveMaxRepos: 10,
      dispatchAllowed: true,
    },
  },
  {
    group: "Kill switch",
    name: "Disabled scheduled review has no capacity",
    inputs: {
      eventName: "schedule",
      configuredMode: "review",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 10,
      packageEnabled: false,
    },
    expected: {
      safeOutputMode: null,
      safeOutputRepo: "",
      effectiveMaxRepos: 0,
      dispatchAllowed: false,
    },
  },
  {
    group: "Kill switch",
    name: "Disabled scheduled live has no capacity",
    inputs: {
      eventName: "schedule",
      configuredMode: "live",
      manualMode: "",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 10,
      packageEnabled: false,
    },
    expected: {
      safeOutputMode: null,
      safeOutputRepo: "",
      effectiveMaxRepos: 0,
      dispatchAllowed: false,
    },
  },
  {
    group: "Kill switch",
    name: "Disabled manual review has no capacity",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "live",
      manualMode: "review",
      manualReviewRepo: "acme/manual-review",
      rolloutPercent: 100,
      maxRepos: 10,
      packageEnabled: false,
    },
    expected: {
      safeOutputMode: null,
      safeOutputRepo: "",
      effectiveMaxRepos: 0,
      dispatchAllowed: false,
    },
  },
  {
    group: "Kill switch",
    name: "Disabled manual live has no capacity",
    inputs: {
      eventName: "workflow_dispatch",
      configuredMode: "review",
      manualMode: "live",
      manualReviewRepo: "",
      rolloutPercent: 100,
      maxRepos: 10,
      packageEnabled: false,
    },
    expected: {
      safeOutputMode: null,
      safeOutputRepo: "",
      effectiveMaxRepos: 0,
      dispatchAllowed: false,
    },
  },
]);

function combinations(dimensions) {
  return dimensions.reduce((rows, [name, values]) => rows.flatMap((row) => values.map((value) => ({ ...row, [name]: value }))), [{}]);
}

export function policyCases() {
  const sharedDimensions = [
    ["configuredMode", policyMatrix.configuredModes],
    ["rolloutPercent", policyMatrix.rolloutPercents],
    ["maxRepos", policyMatrix.maxReposValues],
    ["packageEnabled", policyMatrix.packageEnabledValues],
  ];
  const scheduled = combinations(sharedDimensions).map((values) => ({
    eventName: "schedule",
    manualMode: "",
    manualReviewRepo: "",
    ...values,
  }));
  const manual = combinations([...sharedDimensions, ["manualMode", policyMatrix.selectedModes], ["manualReviewRepo", policyMatrix.manualReviewRepos]]).map(
    (values) => ({ eventName: "workflow_dispatch", ...values }),
  );

  return [...scheduled, ...manual].map((values, index) => ({
    id: `${values.eventName}-${String(index + 1).padStart(3, "0")}`,
    totalRepositories: policyMatrix.totalRepositories,
    ...values,
  }));
}
